/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.OsAvailabilityZoneGet200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for AvailabilityZoneApi
 */
@Ignore
public class AvailabilityZoneApiTest {

    private final AvailabilityZoneApi api = new AvailabilityZoneApi();

    
    /**
     * Получить информацию о зонах доступности
     *
     * 
     */
    @Test
    public void osAvailabilityZoneGetTest()  {
        OsAvailabilityZoneGet200Response response = api.osAvailabilityZoneGet().block();

        // TODO: test validations
    }
    
}
