/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.FlavorDetails;
import org.openapitools.client.model.GetListFlavors;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for FlavorsApi
 */
@Ignore
public class FlavorsApiTest {

    private final FlavorsApi api = new FlavorsApi();

    
    /**
     * Получить список шаблонов конфигураций ВМ с подробной информацией
     *
     * 
     */
    @Test
    public void flavorsDetailGetTest()  {
        String sortKey = null;
        String sortDir = null;
        Integer limit = null;
        String marker = null;
        Integer minDisk = null;
        Integer minRam = null;
        List<FlavorDetails> response = api.flavorsDetailGet(sortKey, sortDir, limit, marker, minDisk, minRam).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Получить информацию о шаблоне конфигурации ВМ
     *
     * 
     */
    @Test
    public void flavorsFlavorIdGetTest()  {
        String flavorId = null;
        FlavorDetails response = api.flavorsFlavorIdGet(flavorId).block();

        // TODO: test validations
    }
    
    /**
     * Получить значение дополнительного параметра шаблона конфигурации ВМ
     *
     * 
     */
    @Test
    public void flavorsFlavorIdOsExtraSpecsExtraSpecKeyGetTest()  {
        UUID flavorId = null;
        String extraSpecKey = null;
        Object response = api.flavorsFlavorIdOsExtraSpecsExtraSpecKeyGet(flavorId, extraSpecKey).block();

        // TODO: test validations
    }
    
    /**
     * Вернуть все дополнительные параметры шаблона конфигурации ВМ
     *
     * 
     */
    @Test
    public void flavorsFlavorIdOsExtraSpecsGetTest()  {
        UUID flavorId = null;
        Object response = api.flavorsFlavorIdOsExtraSpecsGet(flavorId).block();

        // TODO: test validations
    }
    
    /**
     * Получить список шаблонов конфигураций ВМ
     *
     * Метод возвращает список шаблонов конфигураций ВМ по заданным фильтрам
     */
    @Test
    public void flavorsGetTest()  {
        String sortKey = null;
        String sortDir = null;
        Integer limit = null;
        String marker = null;
        Integer minDisk = null;
        Integer minRam = null;
        GetListFlavors response = api.flavorsGet(sortKey, sortDir, limit, marker, minDisk, minRam).block();

        // TODO: test validations
    }
    
}
