/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.OsKeypairsGet200Response;
import org.openapitools.client.model.OsKeypairsKeypairNameGet200Response;
import org.openapitools.client.model.OsKeypairsPost200Response;
import org.openapitools.client.model.OsKeypairsPostRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for KeypairsApi
 */
@Ignore
public class KeypairsApiTest {

    private final KeypairsApi api = new KeypairsApi();

    
    /**
     * Получить список ключевых пар
     *
     * 
     */
    @Test
    public void osKeypairsGetTest()  {
        Integer limit = null;
        String marker = null;
        OsKeypairsGet200Response response = api.osKeypairsGet(limit, marker).block();

        // TODO: test validations
    }
    
    /**
     * Удалить ключевую пару
     *
     * 
     */
    @Test
    public void osKeypairsKeypairNameDeleteTest()  {
        String keypairName = null;
        api.osKeypairsKeypairNameDelete(keypairName).block();

        // TODO: test validations
    }
    
    /**
     * Получить информацию о ключевой паре
     *
     * 
     */
    @Test
    public void osKeypairsKeypairNameGetTest()  {
        String keypairName = null;
        OsKeypairsKeypairNameGet200Response response = api.osKeypairsKeypairNameGet(keypairName).block();

        // TODO: test validations
    }
    
    /**
     * Создать или импортировать ключевую пару
     *
     * 
     */
    @Test
    public void osKeypairsPostTest()  {
        OsKeypairsPostRequest osKeypairsPostRequest = null;
        OsKeypairsPost200Response response = api.osKeypairsPost(osKeypairsPostRequest).block();

        // TODO: test validations
    }
    
}
