/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ServerActionsApi
 */
@Ignore
public class ServerActionsApiTest {

    private final ServerActionsApi api = new ServerActionsApi();

    
    /**
     * Выполнить действие с ВМ
     *
     * Метод позволяет управлять работой ВМ.  Укажите желаемое действие в теле запроса.
     */
    @Test
    public void serversServerIdActionPostTest()  {
        String serverId = null;
        Object body = null;
        api.serversServerIdActionPost(serverId, body).block();

        // TODO: test validations
    }
    
}
