/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.GetListServerDetails;
import org.openapitools.client.model.GetServerDetails;
import org.openapitools.client.model.GetServers;
import org.openapitools.client.model.ServerUpdate;
import org.openapitools.client.model.ServersPostRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ServersApi
 */
@Ignore
public class ServersApiTest {

    private final ServersApi api = new ServersApi();

    
    /**
     * Получить список ВМ с подробной информацией
     *
     * 
     */
    @Test
    public void serversDetailGetTest()  {
        Integer limit = null;
        String marker = null;
        String sortKey = null;
        String sortDir = null;
        String changesSince = null;
        String image = null;
        String flavor = null;
        String name = null;
        String status = null;
        String ip = null;
        String reservationId = null;
        String ip6 = null;
        String tags = null;
        String tagsAny = null;
        String notTags = null;
        String notTagsAny = null;
        String changesBefore = null;
        GetListServerDetails response = api.serversDetailGet(limit, marker, sortKey, sortDir, changesSince, image, flavor, name, status, ip, reservationId, ip6, tags, tagsAny, notTags, notTagsAny, changesBefore).block();

        // TODO: test validations
    }
    
    /**
     * Получить список ВМ
     *
     * 
     */
    @Test
    public void serversGetTest()  {
        Integer limit = null;
        String marker = null;
        String sortKey = null;
        String sortDir = null;
        String changesSince = null;
        String image = null;
        String flavor = null;
        String name = null;
        String status = null;
        String ip = null;
        String reservationId = null;
        String ip6 = null;
        String tags = null;
        String tagsAny = null;
        String notTags = null;
        String notTagsAny = null;
        String changesBefore = null;
        GetServers response = api.serversGet(limit, marker, sortKey, sortDir, changesSince, image, flavor, name, status, ip, reservationId, ip6, tags, tagsAny, notTags, notTagsAny, changesBefore).block();

        // TODO: test validations
    }
    
    /**
     * Создать новую ВМ
     *
     * 
     */
    @Test
    public void serversPostTest()  {
        ServersPostRequest serversPostRequest = null;
        GetServerDetails response = api.serversPost(serversPostRequest).block();

        // TODO: test validations
    }
    
    /**
     * Удалить ВМ
     *
     * 
     */
    @Test
    public void serversServerIdDeleteTest()  {
        String serverId = null;
        api.serversServerIdDelete(serverId).block();

        // TODO: test validations
    }
    
    /**
     * Получить информацию о ВМ
     *
     * 
     */
    @Test
    public void serversServerIdGetTest()  {
        String serverId = null;
        GetServerDetails response = api.serversServerIdGet(serverId).block();

        // TODO: test validations
    }
    
    /**
     * Обновить информацию о ВМ
     *
     * 
     */
    @Test
    public void serversServerIdPutTest()  {
        String serverId = null;
        ServerUpdate serverUpdate = null;
        GetServerDetails response = api.serversServerIdPut(serverId, serverUpdate).block();

        // TODO: test validations
    }
    
}
