/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.OsServerGroupsGet200Response;
import org.openapitools.client.model.OsServerGroupsPost200Response;
import org.openapitools.client.model.OsServerGroupsPostRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ServerGroupsApi
 */
@Ignore
public class ServerGroupsApiTest {

    private final ServerGroupsApi api = new ServerGroupsApi();

    
    /**
     * Получить список групп серверов
     *
     * 
     */
    @Test
    public void osServerGroupsGetTest()  {
        Integer limit = null;
        Integer offset = null;
        OsServerGroupsGet200Response response = api.osServerGroupsGet(limit, offset).block();

        // TODO: test validations
    }
    
    /**
     * Создать группу серверов
     *
     * 
     */
    @Test
    public void osServerGroupsPostTest()  {
        OsServerGroupsPostRequest osServerGroupsPostRequest = null;
        OsServerGroupsPost200Response response = api.osServerGroupsPost(osServerGroupsPostRequest).block();

        // TODO: test validations
    }
    
    /**
     * Удалить группу серверов
     *
     * 
     */
    @Test
    public void osServerGroupsServerGroupIdDeleteTest()  {
        String serverGroupId = null;
        api.osServerGroupsServerGroupIdDelete(serverGroupId).block();

        // TODO: test validations
    }
    
    /**
     * Получить информацию о группе серверов
     *
     * 
     */
    @Test
    public void osServerGroupsServerGroupIdGetTest()  {
        String serverGroupId = null;
        OsServerGroupsPost200Response response = api.osServerGroupsServerGroupIdGet(serverGroupId).block();

        // TODO: test validations
    }
    
}
