/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ServersServerIdOsSecurityGroupsGet200Response;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ServerSecurityGroupsApi
 */
@Ignore
public class ServerSecurityGroupsApiTest {

    private final ServerSecurityGroupsApi api = new ServerSecurityGroupsApi();

    
    /**
     * Получить список групп безопасности ВМ
     *
     * 
     */
    @Test
    public void serversServerIdOsSecurityGroupsGetTest()  {
        String serverId = null;
        ServersServerIdOsSecurityGroupsGet200Response response = api.serversServerIdOsSecurityGroupsGet(serverId).block();

        // TODO: test validations
    }
    
}
