/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Versions;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for VersionsApi
 */
@Ignore
public class VersionsApiTest {

    private final VersionsApi api = new VersionsApi();

    
    /**
     * Подтвердить наличие версии 2.1
     *
     * Метод позволяет подтвердить наличие версии 2.1.  Возвращает код &#x60;&#x60;304 FOUND&#x60;&#x60; и пустое тело ответа
     */
    @Test
    public void apiConfirmV21V21GetTest()  {
        api.apiConfirmV21V21Get().block();

        // TODO: test validations
    }
    
    /**
     * Получить перечень поддерживаемых версий API
     *
     * 
     */
    @Test
    public void rootGetTest()  {
        Versions response = api.rootGet().block();

        // TODO: test validations
    }
    
}
