/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequest;
import org.openapitools.client.model.ServersServerIdOsVolumeAttachmentsGet200Response;
import org.openapitools.client.model.ServersServerIdOsVolumeAttachmentsPost200Response;
import org.openapitools.client.model.ServersServerIdOsVolumeAttachmentsPostRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for VolumeAttachmentsApi
 */
@Ignore
public class VolumeAttachmentsApiTest {

    private final VolumeAttachmentsApi api = new VolumeAttachmentsApi();

    
    /**
     * Отключить диск от ВМ
     *
     * 
     */
    @Test
    public void serversServerIdOsVolumeAttachmentsAttachmentIdDeleteTest()  {
        String serverId = null;
        String attachmentId = null;
        api.serversServerIdOsVolumeAttachmentsAttachmentIdDelete(serverId, attachmentId).block();

        // TODO: test validations
    }
    
    /**
     * Получить информацию о подключении диска к ВМ
     *
     * 
     */
    @Test
    public void serversServerIdOsVolumeAttachmentsAttachmentIdGetTest()  {
        String serverId = null;
        String attachmentId = null;
        ServersServerIdOsVolumeAttachmentsPost200Response response = api.serversServerIdOsVolumeAttachmentsAttachmentIdGet(serverId, attachmentId).block();

        // TODO: test validations
    }
    
    /**
     * Обновить информацию о подключении диска к ВМ
     *
     * 
     */
    @Test
    public void serversServerIdOsVolumeAttachmentsAttachmentIdPutTest()  {
        String serverId = null;
        String attachmentId = null;
        ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequest serversServerIdOsVolumeAttachmentsAttachmentIdPutRequest = null;
        api.serversServerIdOsVolumeAttachmentsAttachmentIdPut(serverId, attachmentId, serversServerIdOsVolumeAttachmentsAttachmentIdPutRequest).block();

        // TODO: test validations
    }
    
    /**
     * Получить список дисков, подключенных к ВМ
     *
     * 
     */
    @Test
    public void serversServerIdOsVolumeAttachmentsGetTest()  {
        String serverId = null;
        ServersServerIdOsVolumeAttachmentsGet200Response response = api.serversServerIdOsVolumeAttachmentsGet(serverId).block();

        // TODO: test validations
    }
    
    /**
     * Подключить диск к ВМ
     *
     * 
     */
    @Test
    public void serversServerIdOsVolumeAttachmentsPostTest()  {
        String serverId = null;
        ServersServerIdOsVolumeAttachmentsPostRequest serversServerIdOsVolumeAttachmentsPostRequest = null;
        ServersServerIdOsVolumeAttachmentsPost200Response response = api.serversServerIdOsVolumeAttachmentsPost(serverId, serversServerIdOsVolumeAttachmentsPostRequest).block();

        // TODO: test validations
    }
    
}
