/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetInstantQueryResponseDataResultInner
 */
@JsonPropertyOrder({
  GetInstantQueryResponseDataResultInner.JSON_PROPERTY_METRIC,
  GetInstantQueryResponseDataResultInner.JSON_PROPERTY_VALUE
})
@JsonTypeName("getInstantQueryResponse_data_result_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:08.670553200+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetInstantQueryResponseDataResultInner {
  public static final String JSON_PROPERTY_METRIC = "metric";
  private Object metric;

  public static final String JSON_PROPERTY_VALUE = "value";
  private List<Object> value;

  public GetInstantQueryResponseDataResultInner() {
  }

  public GetInstantQueryResponseDataResultInner metric(Object metric) {
    
    this.metric = metric;
    return this;
  }

   /**
   * Get metric
   * @return metric
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METRIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetric() {
    return metric;
  }


  @JsonProperty(JSON_PROPERTY_METRIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetric(Object metric) {
    this.metric = metric;
  }


  public GetInstantQueryResponseDataResultInner value(List<Object> value) {
    
    this.value = value;
    return this;
  }

  public GetInstantQueryResponseDataResultInner addValueItem(Object valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(List<Object> value) {
    this.value = value;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInstantQueryResponseDataResultInner getInstantQueryResponseDataResultInner = (GetInstantQueryResponseDataResultInner) o;
    return Objects.equals(this.metric, getInstantQueryResponseDataResultInner.metric) &&
        Objects.equals(this.value, getInstantQueryResponseDataResultInner.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metric, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInstantQueryResponseDataResultInner {\n");
    sb.append("    metric: ").append(toIndentedString(metric)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

