/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetInstantQueryResponseDataResultInner;
import org.openapitools.client.model.ResultType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetInstantQueryResponseData
 */
@JsonPropertyOrder({
  GetInstantQueryResponseData.JSON_PROPERTY_RESULT_TYPE,
  GetInstantQueryResponseData.JSON_PROPERTY_RESULT
})
@JsonTypeName("getInstantQueryResponse_data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:08.670553200+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetInstantQueryResponseData {
  public static final String JSON_PROPERTY_RESULT_TYPE = "resultType";
  private ResultType resultType;

  public static final String JSON_PROPERTY_RESULT = "result";
  private List<GetInstantQueryResponseDataResultInner> result;

  public GetInstantQueryResponseData() {
  }

  public GetInstantQueryResponseData resultType(ResultType resultType) {
    
    this.resultType = resultType;
    return this;
  }

   /**
   * Get resultType
   * @return resultType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ResultType getResultType() {
    return resultType;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultType(ResultType resultType) {
    this.resultType = resultType;
  }


  public GetInstantQueryResponseData result(List<GetInstantQueryResponseDataResultInner> result) {
    
    this.result = result;
    return this;
  }

  public GetInstantQueryResponseData addResultItem(GetInstantQueryResponseDataResultInner resultItem) {
    if (this.result == null) {
      this.result = new ArrayList<>();
    }
    this.result.add(resultItem);
    return this;
  }

   /**
   * Метрики и их значения
   * @return result
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GetInstantQueryResponseDataResultInner> getResult() {
    return result;
  }


  @JsonProperty(JSON_PROPERTY_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResult(List<GetInstantQueryResponseDataResultInner> result) {
    this.result = result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInstantQueryResponseData getInstantQueryResponseData = (GetInstantQueryResponseData) o;
    return Objects.equals(this.resultType, getInstantQueryResponseData.resultType) &&
        Objects.equals(this.result, getInstantQueryResponseData.result);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultType, result);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInstantQueryResponseData {\n");
    sb.append("    resultType: ").append(toIndentedString(resultType)).append("\n");
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

