spring:
  application:
    name: team6

  datasource:
    url: jdbc:postgresql://postgres_db:5432/postgres
    username: user
    password: user
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: user

encryption:
  master-password: root
  salt: 5c0744943158e114
  jwt-key: ${JWT_KEY:mySuperSecretKeyThatIsAtLeast32CharactersLong123!}

springdoc:
  override-with-generic-response: false

server:
  port: 8081
