/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Присвоить ВМ Floating IP-адрес
 */
@JsonPropertyOrder({
  AddFloatingIp.JSON_PROPERTY_ADDRESS,
  AddFloatingIp.JSON_PROPERTY_FIXED_ADDRESS
})
@JsonTypeName("addFloatingIp")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class AddFloatingIp {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_FIXED_ADDRESS = "fixed_address";
  private String fixedAddress;

  public AddFloatingIp() {
  }

  public AddFloatingIp address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Floating IP-адрес
   * @return address
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(String address) {
    this.address = address;
  }


  public AddFloatingIp fixedAddress(String fixedAddress) {
    
    this.fixedAddress = fixedAddress;
    return this;
  }

   /**
   * IP-адрес, к которому будет привязан Floating IP-адрес
   * @return fixedAddress
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIXED_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFixedAddress() {
    return fixedAddress;
  }


  @JsonProperty(JSON_PROPERTY_FIXED_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFixedAddress(String fixedAddress) {
    this.fixedAddress = fixedAddress;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddFloatingIp addFloatingIp = (AddFloatingIp) o;
    return Objects.equals(this.address, addFloatingIp.address) &&
        Objects.equals(this.fixedAddress, addFloatingIp.fixedAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, fixedAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddFloatingIp {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    fixedAddress: ").append(toIndentedString(fixedAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

