/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Изменить пароль &lt;a href&#x3D;&#39;https://cloud.vk.com/docs/ru/computing/iaas/concepts/oper-system#default_account&#39;&gt;учетной записи по умолчанию&lt;/a&gt;
 */
@JsonPropertyOrder({
  ChangePassword.JSON_PROPERTY_ADMIN_PASS
})
@JsonTypeName("changePassword")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ChangePassword {
  public static final String JSON_PROPERTY_ADMIN_PASS = "adminPass";
  private String adminPass;

  public ChangePassword() {
  }

  public ChangePassword adminPass(String adminPass) {
    
    this.adminPass = adminPass;
    return this;
  }

   /**
   * Новый пароль учетной записи по умолчанию
   * @return adminPass
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADMIN_PASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdminPass() {
    return adminPass;
  }


  @JsonProperty(JSON_PROPERTY_ADMIN_PASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdminPass(String adminPass) {
    this.adminPass = adminPass;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePassword changePassword = (ChangePassword) o;
    return Objects.equals(this.adminPass, changePassword.adminPass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adminPass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePassword {\n");
    sb.append("    adminPass: ").append(toIndentedString(adminPass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

