/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FlavorDetails
 */
@JsonPropertyOrder({
  FlavorDetails.JSON_PROPERTY_NAME,
  FlavorDetails.JSON_PROPERTY_ID,
  FlavorDetails.JSON_PROPERTY_RAM,
  FlavorDetails.JSON_PROPERTY_DISK,
  FlavorDetails.JSON_PROPERTY_VCPUS,
  FlavorDetails.JSON_PROPERTY_LINKS,
  FlavorDetails.JSON_PROPERTY_OS_F_L_V_E_X_T_D_A_T_A_COLON_EPHEMERAL,
  FlavorDetails.JSON_PROPERTY_SWAP,
  FlavorDetails.JSON_PROPERTY_RXTX_FACTOR,
  FlavorDetails.JSON_PROPERTY_OS_FLAVOR_ACCESS_COLON_IS_PUBLIC,
  FlavorDetails.JSON_PROPERTY_EXTRA_SPECS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class FlavorDetails {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_RAM = "ram";
  private Integer ram;

  public static final String JSON_PROPERTY_DISK = "disk";
  private Integer disk;

  public static final String JSON_PROPERTY_VCPUS = "vcpus";
  private Integer vcpus;

  public static final String JSON_PROPERTY_LINKS = "links";
  private Object links;

  public static final String JSON_PROPERTY_OS_F_L_V_E_X_T_D_A_T_A_COLON_EPHEMERAL = "OS-FLV-EXT-DATA:ephemeral";
  private Integer osFLVEXTDATAColonEphemeral = 0;

  public static final String JSON_PROPERTY_SWAP = "swap";
  private Integer swap = 0;

  public static final String JSON_PROPERTY_RXTX_FACTOR = "rxtx_factor";
  private BigDecimal rxtxFactor = new BigDecimal("1.0");

  public static final String JSON_PROPERTY_OS_FLAVOR_ACCESS_COLON_IS_PUBLIC = "os-flavor-access:is_public";
  private Boolean osFlavorAccessColonIsPublic = true;

  public static final String JSON_PROPERTY_EXTRA_SPECS = "extra_specs";
  private Object extraSpecs;

  public FlavorDetails() {
  }

  public FlavorDetails name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Имя шаблона конфигурации ВМ
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public FlavorDetails id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Идентификатор шаблона конфигурации ВМ
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public FlavorDetails ram(Integer ram) {
    
    this.ram = ram;
    return this;
  }

   /**
   * Количество RAM в мебибайтах
   * @return ram
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RAM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRam() {
    return ram;
  }


  @JsonProperty(JSON_PROPERTY_RAM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRam(Integer ram) {
    this.ram = ram;
  }


  public FlavorDetails disk(Integer disk) {
    
    this.disk = disk;
    return this;
  }

   /**
   * Размер диска в гигибайтах
   * @return disk
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDisk() {
    return disk;
  }


  @JsonProperty(JSON_PROPERTY_DISK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisk(Integer disk) {
    this.disk = disk;
  }


  public FlavorDetails vcpus(Integer vcpus) {
    
    this.vcpus = vcpus;
    return this;
  }

   /**
   * Количество виртуальных процессоров
   * @return vcpus
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VCPUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getVcpus() {
    return vcpus;
  }


  @JsonProperty(JSON_PROPERTY_VCPUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVcpus(Integer vcpus) {
    this.vcpus = vcpus;
  }


  public FlavorDetails links(Object links) {
    
    this.links = links;
    return this;
  }

   /**
   * Ссылки на рассматриваемые ресурсы. Дополнительная информация — http:developer.openstack.org/api-guide/compute/links_and_references.html
   * @return links
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLinks(Object links) {
    this.links = links;
  }


  public FlavorDetails osFLVEXTDATAColonEphemeral(Integer osFLVEXTDATAColonEphemeral) {
    
    this.osFLVEXTDATAColonEphemeral = osFLVEXTDATAColonEphemeral;
    return this;
  }

   /**
   * Размер эфемерного диска
   * @return osFLVEXTDATAColonEphemeral
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OS_F_L_V_E_X_T_D_A_T_A_COLON_EPHEMERAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getOsFLVEXTDATAColonEphemeral() {
    return osFLVEXTDATAColonEphemeral;
  }


  @JsonProperty(JSON_PROPERTY_OS_F_L_V_E_X_T_D_A_T_A_COLON_EPHEMERAL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOsFLVEXTDATAColonEphemeral(Integer osFLVEXTDATAColonEphemeral) {
    this.osFLVEXTDATAColonEphemeral = osFLVEXTDATAColonEphemeral;
  }


  public FlavorDetails swap(Integer swap) {
    
    this.swap = swap;
    return this;
  }

   /**
   * Размер swap-диска. Если &#x60;&#x60;0&#x60;&#x60;, swap-диск не будет создан
   * @return swap
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SWAP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSwap() {
    return swap;
  }


  @JsonProperty(JSON_PROPERTY_SWAP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSwap(Integer swap) {
    this.swap = swap;
  }


  public FlavorDetails rxtxFactor(BigDecimal rxtxFactor) {
    
    this.rxtxFactor = rxtxFactor;
    return this;
  }

   /**
   * Коэффициент приема/передачи, который будет установлен на портах, если поддерживается расширение QOS
   * @return rxtxFactor
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RXTX_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getRxtxFactor() {
    return rxtxFactor;
  }


  @JsonProperty(JSON_PROPERTY_RXTX_FACTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRxtxFactor(BigDecimal rxtxFactor) {
    this.rxtxFactor = rxtxFactor;
  }


  public FlavorDetails osFlavorAccessColonIsPublic(Boolean osFlavorAccessColonIsPublic) {
    
    this.osFlavorAccessColonIsPublic = osFlavorAccessColonIsPublic;
    return this;
  }

   /**
   * Указывает, является ли шаблон конфигурации ВМ общедоступным
   * @return osFlavorAccessColonIsPublic
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OS_FLAVOR_ACCESS_COLON_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getOsFlavorAccessColonIsPublic() {
    return osFlavorAccessColonIsPublic;
  }


  @JsonProperty(JSON_PROPERTY_OS_FLAVOR_ACCESS_COLON_IS_PUBLIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOsFlavorAccessColonIsPublic(Boolean osFlavorAccessColonIsPublic) {
    this.osFlavorAccessColonIsPublic = osFlavorAccessColonIsPublic;
  }


  public FlavorDetails extraSpecs(Object extraSpecs) {
    
    this.extraSpecs = extraSpecs;
    return this;
  }

   /**
   * Дополнительные сведения о шаблоне конфигурации ВМ
   * @return extraSpecs
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXTRA_SPECS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getExtraSpecs() {
    return extraSpecs;
  }


  @JsonProperty(JSON_PROPERTY_EXTRA_SPECS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExtraSpecs(Object extraSpecs) {
    this.extraSpecs = extraSpecs;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FlavorDetails flavorDetails = (FlavorDetails) o;
    return Objects.equals(this.name, flavorDetails.name) &&
        Objects.equals(this.id, flavorDetails.id) &&
        Objects.equals(this.ram, flavorDetails.ram) &&
        Objects.equals(this.disk, flavorDetails.disk) &&
        Objects.equals(this.vcpus, flavorDetails.vcpus) &&
        Objects.equals(this.links, flavorDetails.links) &&
        Objects.equals(this.osFLVEXTDATAColonEphemeral, flavorDetails.osFLVEXTDATAColonEphemeral) &&
        Objects.equals(this.swap, flavorDetails.swap) &&
        Objects.equals(this.rxtxFactor, flavorDetails.rxtxFactor) &&
        Objects.equals(this.osFlavorAccessColonIsPublic, flavorDetails.osFlavorAccessColonIsPublic) &&
        Objects.equals(this.extraSpecs, flavorDetails.extraSpecs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, ram, disk, vcpus, links, osFLVEXTDATAColonEphemeral, swap, rxtxFactor, osFlavorAccessColonIsPublic, extraSpecs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FlavorDetails {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ram: ").append(toIndentedString(ram)).append("\n");
    sb.append("    disk: ").append(toIndentedString(disk)).append("\n");
    sb.append("    vcpus: ").append(toIndentedString(vcpus)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    osFLVEXTDATAColonEphemeral: ").append(toIndentedString(osFLVEXTDATAColonEphemeral)).append("\n");
    sb.append("    swap: ").append(toIndentedString(swap)).append("\n");
    sb.append("    rxtxFactor: ").append(toIndentedString(rxtxFactor)).append("\n");
    sb.append("    osFlavorAccessColonIsPublic: ").append(toIndentedString(osFlavorAccessColonIsPublic)).append("\n");
    sb.append("    extraSpecs: ").append(toIndentedString(extraSpecs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

