/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetAvailabilityZoneZoneState;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Зона доступности
 */
@JsonPropertyOrder({
  GetAvailabilityZone.JSON_PROPERTY_HOSTS,
  GetAvailabilityZone.JSON_PROPERTY_ZONE_NAME,
  GetAvailabilityZone.JSON_PROPERTY_ZONE_STATE
})
@JsonTypeName("getAvailabilityZone")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetAvailabilityZone {
  /**
   * 
   */
  public enum HostsEnum {
    NULL("null");

    private String value;

    HostsEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HostsEnum fromValue(String value) {
      for (HostsEnum b : HostsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_HOSTS = "hosts";
  private JsonNullable<HostsEnum> hosts = JsonNullable.<HostsEnum>undefined();

  public static final String JSON_PROPERTY_ZONE_NAME = "zoneName";
  private String zoneName;

  public static final String JSON_PROPERTY_ZONE_STATE = "zoneState";
  private GetAvailabilityZoneZoneState zoneState;

  public GetAvailabilityZone() {
  }

  public GetAvailabilityZone hosts(HostsEnum hosts) {
    this.hosts = JsonNullable.<HostsEnum>of(hosts);
    
    return this;
  }

   /**
   * 
   * @return hosts
  **/
  @javax.annotation.Nullable
  @JsonIgnore

  public HostsEnum getHosts() {
        return hosts.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_HOSTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<HostsEnum> getHosts_JsonNullable() {
    return hosts;
  }
  
  @JsonProperty(JSON_PROPERTY_HOSTS)
  public void setHosts_JsonNullable(JsonNullable<HostsEnum> hosts) {
    this.hosts = hosts;
  }

  public void setHosts(HostsEnum hosts) {
    this.hosts = JsonNullable.<HostsEnum>of(hosts);
  }


  public GetAvailabilityZone zoneName(String zoneName) {
    
    this.zoneName = zoneName;
    return this;
  }

   /**
   * Имя зоны доступности
   * @return zoneName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZONE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZoneName() {
    return zoneName;
  }


  @JsonProperty(JSON_PROPERTY_ZONE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZoneName(String zoneName) {
    this.zoneName = zoneName;
  }


  public GetAvailabilityZone zoneState(GetAvailabilityZoneZoneState zoneState) {
    
    this.zoneState = zoneState;
    return this;
  }

   /**
   * Get zoneState
   * @return zoneState
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZONE_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetAvailabilityZoneZoneState getZoneState() {
    return zoneState;
  }


  @JsonProperty(JSON_PROPERTY_ZONE_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZoneState(GetAvailabilityZoneZoneState zoneState) {
    this.zoneState = zoneState;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAvailabilityZone getAvailabilityZone = (GetAvailabilityZone) o;
    return equalsNullable(this.hosts, getAvailabilityZone.hosts) &&
        Objects.equals(this.zoneName, getAvailabilityZone.zoneName) &&
        Objects.equals(this.zoneState, getAvailabilityZone.zoneState);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(hosts), zoneName, zoneState);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAvailabilityZone {\n");
    sb.append("    hosts: ").append(toIndentedString(hosts)).append("\n");
    sb.append("    zoneName: ").append(toIndentedString(zoneName)).append("\n");
    sb.append("    zoneState: ").append(toIndentedString(zoneState)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

