/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetFlavorsFlavorsInner
 */
@JsonPropertyOrder({
  GetFlavorsFlavorsInner.JSON_PROPERTY_ID,
  GetFlavorsFlavorsInner.JSON_PROPERTY_LINKS,
  GetFlavorsFlavorsInner.JSON_PROPERTY_NAME
})
@JsonTypeName("getFlavors_flavors_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetFlavorsFlavorsInner {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LINKS = "links";
  private Object links;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public GetFlavorsFlavorsInner() {
  }

  public GetFlavorsFlavorsInner id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Идентификатор шаблона конфигурации ВМ
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GetFlavorsFlavorsInner links(Object links) {
    
    this.links = links;
    return this;
  }

   /**
   * Ссылки на рассматриваемые ресурсы. Дополнительная информация — &#x60;http:developer.openstack.org/api-guide/compute/links_and_references.html&#x60;
   * @return links
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(Object links) {
    this.links = links;
  }


  public GetFlavorsFlavorsInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Имя шаблона конфигурации ВМ
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFlavorsFlavorsInner getFlavorsFlavorsInner = (GetFlavorsFlavorsInner) o;
    return Objects.equals(this.id, getFlavorsFlavorsInner.id) &&
        Objects.equals(this.links, getFlavorsFlavorsInner.links) &&
        Objects.equals(this.name, getFlavorsFlavorsInner.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, links, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFlavorsFlavorsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

