/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ServerDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetListFlavors
 */
@JsonPropertyOrder({
  GetListFlavors.JSON_PROPERTY_FLAVORS
})
@JsonTypeName("getListFlavors")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetListFlavors {
  public static final String JSON_PROPERTY_FLAVORS = "flavors";
  private List<ServerDetails> flavors;

  public GetListFlavors() {
  }

  public GetListFlavors flavors(List<ServerDetails> flavors) {
    
    this.flavors = flavors;
    return this;
  }

  public GetListFlavors addFlavorsItem(ServerDetails flavorsItem) {
    if (this.flavors == null) {
      this.flavors = new ArrayList<>();
    }
    this.flavors.add(flavorsItem);
    return this;
  }

   /**
   * Список шаблонов конфигураций ВМ
   * @return flavors
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLAVORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ServerDetails> getFlavors() {
    return flavors;
  }


  @JsonProperty(JSON_PROPERTY_FLAVORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlavors(List<ServerDetails> flavors) {
    this.flavors = flavors;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetListFlavors getListFlavors = (GetListFlavors) o;
    return Objects.equals(this.flavors, getListFlavors.flavors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flavors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetListFlavors {\n");
    sb.append("    flavors: ").append(toIndentedString(flavors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

