/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Группа серверов
 */
@JsonPropertyOrder({
  GetServerGroups.JSON_PROPERTY_ID,
  GetServerGroups.JSON_PROPERTY_NAME,
  GetServerGroups.JSON_PROPERTY_POLICIES,
  GetServerGroups.JSON_PROPERTY_MEMBERS,
  GetServerGroups.JSON_PROPERTY_METADATA,
  GetServerGroups.JSON_PROPERTY_PROJECT_ID
})
@JsonTypeName("getServerGroups")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetServerGroups {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  /**
   * Gets or Sets policies
   */
  public enum PoliciesEnum {
    AFFINITY("affinity"),
    
    ANTI_AFFINITY("anti-affinity"),
    
    SOFT_AFFINITY("soft-affinity"),
    
    SOFT_ANTI_AFFINITY("soft-anti-affinity");

    private String value;

    PoliciesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PoliciesEnum fromValue(String value) {
      for (PoliciesEnum b : PoliciesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_POLICIES = "policies";
  private List<PoliciesEnum> policies = new ArrayList<>();

  public static final String JSON_PROPERTY_MEMBERS = "members";
  private List<String> members = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, String> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_PROJECT_ID = "project_id";
  private String projectId;

  public GetServerGroups() {
  }

  public GetServerGroups id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Идентификатор группы серверов
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public GetServerGroups name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Имя группы серверов
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public GetServerGroups policies(List<PoliciesEnum> policies) {
    
    this.policies = policies;
    return this;
  }

  public GetServerGroups addPoliciesItem(PoliciesEnum policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Список политик размещения группы серверов на вычислительных узлах
   * @return policies
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_POLICIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PoliciesEnum> getPolicies() {
    return policies;
  }


  @JsonProperty(JSON_PROPERTY_POLICIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPolicies(List<PoliciesEnum> policies) {
    this.policies = policies;
  }


  public GetServerGroups members(List<String> members) {
    
    this.members = members;
    return this;
  }

  public GetServerGroups addMembersItem(String membersItem) {
    if (this.members == null) {
      this.members = new ArrayList<>();
    }
    this.members.add(membersItem);
    return this;
  }

   /**
   * Список ВМ, входящих в группу
   * @return members
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMembers() {
    return members;
  }


  @JsonProperty(JSON_PROPERTY_MEMBERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMembers(List<String> members) {
    this.members = members;
  }


  public GetServerGroups metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public GetServerGroups putMetadataItem(String key, String metadataItem) {
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Метаданные группы серверов
   * @return metadata
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public GetServerGroups projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Значение параметра &lt;a href&#x3D;&#39;https://cloud.vk.com/docs/tools-for-using-services/api/rest-api/endpoints#poluchenie_project_id&#39;&gt;Project ID&lt;/a&gt; для проекта
   * @return projectId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProjectId() {
    return projectId;
  }


  @JsonProperty(JSON_PROPERTY_PROJECT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetServerGroups getServerGroups = (GetServerGroups) o;
    return Objects.equals(this.id, getServerGroups.id) &&
        Objects.equals(this.name, getServerGroups.name) &&
        Objects.equals(this.policies, getServerGroups.policies) &&
        Objects.equals(this.members, getServerGroups.members) &&
        Objects.equals(this.metadata, getServerGroups.metadata) &&
        Objects.equals(this.projectId, getServerGroups.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, policies, members, metadata, projectId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetServerGroups {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    members: ").append(toIndentedString(members)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

