/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * GetVolumesAttachments
 */
@JsonPropertyOrder({
  GetVolumesAttachments.JSON_PROPERTY_DEVICE,
  GetVolumesAttachments.JSON_PROPERTY_ID,
  GetVolumesAttachments.JSON_PROPERTY_SERVER_ID,
  GetVolumesAttachments.JSON_PROPERTY_VOLUME_ID
})
@JsonTypeName("getVolumesAttachments")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class GetVolumesAttachments {
  public static final String JSON_PROPERTY_DEVICE = "device";
  private String device;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_SERVER_ID = "serverId";
  private String serverId;

  public static final String JSON_PROPERTY_VOLUME_ID = "volumeId";
  private String volumeId;

  public GetVolumesAttachments() {
  }

  public GetVolumesAttachments device(String device) {
    
    this.device = device;
    return this;
  }

   /**
   * Имя устройства
   * @return device
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDevice() {
    return device;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(String device) {
    this.device = device;
  }


  public GetVolumesAttachments id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Идентификатор подключения диска
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public GetVolumesAttachments serverId(String serverId) {
    
    this.serverId = serverId;
    return this;
  }

   /**
   * Идентификатор ВМ
   * @return serverId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getServerId() {
    return serverId;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerId(String serverId) {
    this.serverId = serverId;
  }


  public GetVolumesAttachments volumeId(String volumeId) {
    
    this.volumeId = volumeId;
    return this;
  }

   /**
   * Идентификатор диска
   * @return volumeId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VOLUME_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVolumeId() {
    return volumeId;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeId(String volumeId) {
    this.volumeId = volumeId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetVolumesAttachments getVolumesAttachments = (GetVolumesAttachments) o;
    return Objects.equals(this.device, getVolumesAttachments.device) &&
        Objects.equals(this.id, getVolumesAttachments.id) &&
        Objects.equals(this.serverId, getVolumesAttachments.serverId) &&
        Objects.equals(this.volumeId, getVolumesAttachments.volumeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(device, id, serverId, volumeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetVolumesAttachments {\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    serverId: ").append(toIndentedString(serverId)).append("\n");
    sb.append("    volumeId: ").append(toIndentedString(volumeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

