/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetAvailabilityZone;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OsAvailabilityZoneGet200Response
 */
@JsonPropertyOrder({
  OsAvailabilityZoneGet200Response.JSON_PROPERTY_AVAILABILITY_ZONE_INFO
})
@JsonTypeName("_os_availability_zone_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class OsAvailabilityZoneGet200Response {
  public static final String JSON_PROPERTY_AVAILABILITY_ZONE_INFO = "availabilityZoneInfo";
  private List<GetAvailabilityZone> availabilityZoneInfo = new ArrayList<>();

  public OsAvailabilityZoneGet200Response() {
  }

  public OsAvailabilityZoneGet200Response availabilityZoneInfo(List<GetAvailabilityZone> availabilityZoneInfo) {
    
    this.availabilityZoneInfo = availabilityZoneInfo;
    return this;
  }

  public OsAvailabilityZoneGet200Response addAvailabilityZoneInfoItem(GetAvailabilityZone availabilityZoneInfoItem) {
    if (this.availabilityZoneInfo == null) {
      this.availabilityZoneInfo = new ArrayList<>();
    }
    this.availabilityZoneInfo.add(availabilityZoneInfoItem);
    return this;
  }

   /**
   * Get availabilityZoneInfo
   * @return availabilityZoneInfo
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AVAILABILITY_ZONE_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetAvailabilityZone> getAvailabilityZoneInfo() {
    return availabilityZoneInfo;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABILITY_ZONE_INFO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAvailabilityZoneInfo(List<GetAvailabilityZone> availabilityZoneInfo) {
    this.availabilityZoneInfo = availabilityZoneInfo;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OsAvailabilityZoneGet200Response osAvailabilityZoneGet200Response = (OsAvailabilityZoneGet200Response) o;
    return Objects.equals(this.availabilityZoneInfo, osAvailabilityZoneGet200Response.availabilityZoneInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availabilityZoneInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OsAvailabilityZoneGet200Response {\n");
    sb.append("    availabilityZoneInfo: ").append(toIndentedString(availabilityZoneInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

