/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CreateKeypairs;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OsKeypairsPost200Response
 */
@JsonPropertyOrder({
  OsKeypairsPost200Response.JSON_PROPERTY_KEYPAIR
})
@JsonTypeName("_os_keypairs_post_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class OsKeypairsPost200Response {
  public static final String JSON_PROPERTY_KEYPAIR = "keypair";
  private CreateKeypairs keypair;

  public OsKeypairsPost200Response() {
  }

  public OsKeypairsPost200Response keypair(CreateKeypairs keypair) {
    
    this.keypair = keypair;
    return this;
  }

   /**
   * Get keypair
   * @return keypair
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEYPAIR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CreateKeypairs getKeypair() {
    return keypair;
  }


  @JsonProperty(JSON_PROPERTY_KEYPAIR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeypair(CreateKeypairs keypair) {
    this.keypair = keypair;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OsKeypairsPost200Response osKeypairsPost200Response = (OsKeypairsPost200Response) o;
    return Objects.equals(this.keypair, osKeypairsPost200Response.keypair);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keypair);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OsKeypairsPost200Response {\n");
    sb.append("    keypair: ").append(toIndentedString(keypair)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

