/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetKeypairs;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OsKeypairsGet200Response
 */
@JsonPropertyOrder({
  OsKeypairsGet200Response.JSON_PROPERTY_KEYPAIRS,
  OsKeypairsGet200Response.JSON_PROPERTY_KEYPAIRS_LINKS
})
@JsonTypeName("_os_keypairs_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class OsKeypairsGet200Response {
  public static final String JSON_PROPERTY_KEYPAIRS = "keypairs";
  private List<GetKeypairs> keypairs = new ArrayList<>();

  public static final String JSON_PROPERTY_KEYPAIRS_LINKS = "keypairs_links";
  private List<Object> keypairsLinks;

  public OsKeypairsGet200Response() {
  }

  public OsKeypairsGet200Response keypairs(List<GetKeypairs> keypairs) {
    
    this.keypairs = keypairs;
    return this;
  }

  public OsKeypairsGet200Response addKeypairsItem(GetKeypairs keypairsItem) {
    if (this.keypairs == null) {
      this.keypairs = new ArrayList<>();
    }
    this.keypairs.add(keypairsItem);
    return this;
  }

   /**
   * Get keypairs
   * @return keypairs
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_KEYPAIRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetKeypairs> getKeypairs() {
    return keypairs;
  }


  @JsonProperty(JSON_PROPERTY_KEYPAIRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKeypairs(List<GetKeypairs> keypairs) {
    this.keypairs = keypairs;
  }


  public OsKeypairsGet200Response keypairsLinks(List<Object> keypairsLinks) {
    
    this.keypairsLinks = keypairsLinks;
    return this;
  }

  public OsKeypairsGet200Response addKeypairsLinksItem(Object keypairsLinksItem) {
    if (this.keypairsLinks == null) {
      this.keypairsLinks = new ArrayList<>();
    }
    this.keypairsLinks.add(keypairsLinksItem);
    return this;
  }

   /**
   * Get keypairsLinks
   * @return keypairsLinks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYPAIRS_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getKeypairsLinks() {
    return keypairsLinks;
  }


  @JsonProperty(JSON_PROPERTY_KEYPAIRS_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeypairsLinks(List<Object> keypairsLinks) {
    this.keypairsLinks = keypairsLinks;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OsKeypairsGet200Response osKeypairsGet200Response = (OsKeypairsGet200Response) o;
    return Objects.equals(this.keypairs, osKeypairsGet200Response.keypairs) &&
        Objects.equals(this.keypairsLinks, osKeypairsGet200Response.keypairsLinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keypairs, keypairsLinks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OsKeypairsGet200Response {\n");
    sb.append("    keypairs: ").append(toIndentedString(keypairs)).append("\n");
    sb.append("    keypairsLinks: ").append(toIndentedString(keypairsLinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

