/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.OsServerGroupsPostRequestServerGroup;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OsServerGroupsPostRequest
 */
@JsonPropertyOrder({
  OsServerGroupsPostRequest.JSON_PROPERTY_SERVER_GROUP
})
@JsonTypeName("_os_server_groups_post_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class OsServerGroupsPostRequest {
  public static final String JSON_PROPERTY_SERVER_GROUP = "server_group";
  private OsServerGroupsPostRequestServerGroup serverGroup;

  public OsServerGroupsPostRequest() {
  }

  public OsServerGroupsPostRequest serverGroup(OsServerGroupsPostRequestServerGroup serverGroup) {
    
    this.serverGroup = serverGroup;
    return this;
  }

   /**
   * Get serverGroup
   * @return serverGroup
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SERVER_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OsServerGroupsPostRequestServerGroup getServerGroup() {
    return serverGroup;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServerGroup(OsServerGroupsPostRequestServerGroup serverGroup) {
    this.serverGroup = serverGroup;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OsServerGroupsPostRequest osServerGroupsPostRequest = (OsServerGroupsPostRequest) o;
    return Objects.equals(this.serverGroup, osServerGroupsPostRequest.serverGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverGroup);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OsServerGroupsPostRequest {\n");
    sb.append("    serverGroup: ").append(toIndentedString(serverGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

