/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetServerGroups;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * OsServerGroupsGet200Response
 */
@JsonPropertyOrder({
  OsServerGroupsGet200Response.JSON_PROPERTY_SERVER_GROUPS
})
@JsonTypeName("_os_server_groups_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class OsServerGroupsGet200Response {
  public static final String JSON_PROPERTY_SERVER_GROUPS = "server_groups";
  private List<GetServerGroups> serverGroups = new ArrayList<>();

  public OsServerGroupsGet200Response() {
  }

  public OsServerGroupsGet200Response serverGroups(List<GetServerGroups> serverGroups) {
    
    this.serverGroups = serverGroups;
    return this;
  }

  public OsServerGroupsGet200Response addServerGroupsItem(GetServerGroups serverGroupsItem) {
    if (this.serverGroups == null) {
      this.serverGroups = new ArrayList<>();
    }
    this.serverGroups.add(serverGroupsItem);
    return this;
  }

   /**
   * Список групп серверов
   * @return serverGroups
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SERVER_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<GetServerGroups> getServerGroups() {
    return serverGroups;
  }


  @JsonProperty(JSON_PROPERTY_SERVER_GROUPS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setServerGroups(List<GetServerGroups> serverGroups) {
    this.serverGroups = serverGroups;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OsServerGroupsGet200Response osServerGroupsGet200Response = (OsServerGroupsGet200Response) o;
    return Objects.equals(this.serverGroups, osServerGroupsGet200Response.serverGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverGroups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OsServerGroupsGet200Response {\n");
    sb.append("    serverGroups: ").append(toIndentedString(serverGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

