/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Перезапустить ВМ
 */
@JsonPropertyOrder({
  RebootVM.JSON_PROPERTY_TYPE
})
@JsonTypeName("rebootVM")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class RebootVM {
  /**
   * Тип перезапуска ВМ. Значение &#x60;&#x60;SOFT&#x60;&#x60; применимо только к ВМ в статусе &#x60;&#x60;ACTIVE&#x60;&#x60;. Значение &#x60;&#x60;HARD&#x60;&#x60; применимо к ВМ в статусах &#x60;&#x60;ACTIVE&#x60;&#x60;, &#x60;&#x60;ERROR&#x60;&#x60;, &#x60;&#x60;HARD_REBOOT&#x60;&#x60;, &#x60;&#x60;PAUSED&#x60;&#x60;, &#x60;&#x60;REBOOT&#x60;&#x60;, &#x60;&#x60;SHUTOFF&#x60;&#x60; и &#x60;&#x60;SUSPENDED&#x60;&#x60;
   */
  public enum TypeEnum {
    HARD("HARD"),
    
    SOFT("SOFT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public RebootVM() {
  }

  public RebootVM type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * Тип перезапуска ВМ. Значение &#x60;&#x60;SOFT&#x60;&#x60; применимо только к ВМ в статусе &#x60;&#x60;ACTIVE&#x60;&#x60;. Значение &#x60;&#x60;HARD&#x60;&#x60; применимо к ВМ в статусах &#x60;&#x60;ACTIVE&#x60;&#x60;, &#x60;&#x60;ERROR&#x60;&#x60;, &#x60;&#x60;HARD_REBOOT&#x60;&#x60;, &#x60;&#x60;PAUSED&#x60;&#x60;, &#x60;&#x60;REBOOT&#x60;&#x60;, &#x60;&#x60;SHUTOFF&#x60;&#x60; и &#x60;&#x60;SUSPENDED&#x60;&#x60;
   * @return type
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(TypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RebootVM rebootVM = (RebootVM) o;
    return Objects.equals(this.type, rebootVM.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RebootVM {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

