/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Изменить шаблон конфигурации ВМ
 */
@JsonPropertyOrder({
  ResizeVM.JSON_PROPERTY_FLAVOR_REF,
  ResizeVM.JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG
})
@JsonTypeName("resizeVM")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ResizeVM {
  public static final String JSON_PROPERTY_FLAVOR_REF = "flavorRef";
  private String flavorRef;

  /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   */
  public enum OsDCFColonDiskConfigEnum {
    AUTO("AUTO"),
    
    MANUAL("MANUAL");

    private String value;

    OsDCFColonDiskConfigEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OsDCFColonDiskConfigEnum fromValue(String value) {
      for (OsDCFColonDiskConfigEnum b : OsDCFColonDiskConfigEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG = "OS-DCF:diskConfig";
  private OsDCFColonDiskConfigEnum osDCFColonDiskConfig;

  public ResizeVM() {
  }

  public ResizeVM flavorRef(String flavorRef) {
    
    this.flavorRef = flavorRef;
    return this;
  }

   /**
   * Идентификатор шаблона конфигурации ВМ
   * @return flavorRef
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLAVOR_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlavorRef() {
    return flavorRef;
  }


  @JsonProperty(JSON_PROPERTY_FLAVOR_REF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlavorRef(String flavorRef) {
    this.flavorRef = flavorRef;
  }


  public ResizeVM osDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
    return this;
  }

   /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   * @return osDCFColonDiskConfig
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OsDCFColonDiskConfigEnum getOsDCFColonDiskConfig() {
    return osDCFColonDiskConfig;
  }


  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResizeVM resizeVM = (ResizeVM) o;
    return Objects.equals(this.flavorRef, resizeVM.flavorRef) &&
        Objects.equals(this.osDCFColonDiskConfig, resizeVM.osDCFColonDiskConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(flavorRef, osDCFColonDiskConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResizeVM {\n");
    sb.append("    flavorRef: ").append(toIndentedString(flavorRef)).append("\n");
    sb.append("    osDCFColonDiskConfig: ").append(toIndentedString(osDCFColonDiskConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

