/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment
 */
@JsonPropertyOrder({
  ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment.JSON_PROPERTY_VOLUME_ID
})
@JsonTypeName("_servers__server_id__os_volume_attachments__attachment_id__put_request_volumeAttachment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment {
  public static final String JSON_PROPERTY_VOLUME_ID = "volumeId";
  private String volumeId;

  public ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment() {
  }

  public ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment volumeId(String volumeId) {
    
    this.volumeId = volumeId;
    return this;
  }

   /**
   * Идентификатор диска, который нужно подключить
   * @return volumeId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VOLUME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVolumeId() {
    return volumeId;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVolumeId(String volumeId) {
    this.volumeId = volumeId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment serversServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment = (ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment) o;
    return Objects.equals(this.volumeId, serversServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment.volumeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volumeId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersServerIdOsVolumeAttachmentsAttachmentIdPutRequestVolumeAttachment {\n");
    sb.append("    volumeId: ").append(toIndentedString(volumeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

