/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment
 */
@JsonPropertyOrder({
  ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment.JSON_PROPERTY_VOLUME_ID,
  ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment.JSON_PROPERTY_DEVICE
})
@JsonTypeName("_servers__server_id__os_volume_attachments_post_request_volumeAttachment")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment {
  public static final String JSON_PROPERTY_VOLUME_ID = "volumeId";
  private String volumeId;

  public static final String JSON_PROPERTY_DEVICE = "device";
  private String device;

  public ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment() {
  }

  public ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment volumeId(String volumeId) {
    
    this.volumeId = volumeId;
    return this;
  }

   /**
   * Идентификатор диска
   * @return volumeId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VOLUME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVolumeId() {
    return volumeId;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVolumeId(String volumeId) {
    this.volumeId = volumeId;
  }


  public ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment device(String device) {
    
    this.device = device;
    return this;
  }

   /**
   * Имя устройства
   * @return device
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDevice() {
    return device;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevice(String device) {
    this.device = device;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment serversServerIdOsVolumeAttachmentsPostRequestVolumeAttachment = (ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment) o;
    return Objects.equals(this.volumeId, serversServerIdOsVolumeAttachmentsPostRequestVolumeAttachment.volumeId) &&
        Objects.equals(this.device, serversServerIdOsVolumeAttachmentsPostRequestVolumeAttachment.device);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volumeId, device);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment {\n");
    sb.append("    volumeId: ").append(toIndentedString(volumeId)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

