/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ServersPostRequestServerBlockDeviceMappingV2Inner;
import org.openapitools.client.model.ServersPostRequestServerNetworksInner;
import org.openapitools.client.model.ServersPostRequestServerSecurityGroupsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersPostRequestServer
 */
@JsonPropertyOrder({
  ServersPostRequestServer.JSON_PROPERTY_NAME,
  ServersPostRequestServer.JSON_PROPERTY_FLAVOR_REF,
  ServersPostRequestServer.JSON_PROPERTY_IMAGE_REF,
  ServersPostRequestServer.JSON_PROPERTY_SECURITY_GROUPS,
  ServersPostRequestServer.JSON_PROPERTY_METADATA,
  ServersPostRequestServer.JSON_PROPERTY_ACCESS_I_PV4,
  ServersPostRequestServer.JSON_PROPERTY_ACCESS_I_PV6,
  ServersPostRequestServer.JSON_PROPERTY_ADMIN_PASS,
  ServersPostRequestServer.JSON_PROPERTY_USER_DATA,
  ServersPostRequestServer.JSON_PROPERTY_AVAILABILITY_ZONE,
  ServersPostRequestServer.JSON_PROPERTY_CONFIG_DRIVE,
  ServersPostRequestServer.JSON_PROPERTY_NETWORKS,
  ServersPostRequestServer.JSON_PROPERTY_PERSONALITY,
  ServersPostRequestServer.JSON_PROPERTY_BLOCK_DEVICE_MAPPING_V2,
  ServersPostRequestServer.JSON_PROPERTY_KEY_NAME,
  ServersPostRequestServer.JSON_PROPERTY_OS_COLON_SCHEDULER_HINTS,
  ServersPostRequestServer.JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG,
  ServersPostRequestServer.JSON_PROPERTY_DESCRIPTION,
  ServersPostRequestServer.JSON_PROPERTY_TAGS
})
@JsonTypeName("_servers_post_request_server")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersPostRequestServer {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_FLAVOR_REF = "flavorRef";
  private String flavorRef;

  public static final String JSON_PROPERTY_IMAGE_REF = "imageRef";
  private String imageRef;

  public static final String JSON_PROPERTY_SECURITY_GROUPS = "security_groups";
  private List<ServersPostRequestServerSecurityGroupsInner> securityGroups;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, String> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_ACCESS_I_PV4 = "accessIPv4";
  private String accessIPv4;

  public static final String JSON_PROPERTY_ACCESS_I_PV6 = "accessIPv6";
  private String accessIPv6;

  public static final String JSON_PROPERTY_ADMIN_PASS = "adminPass";
  private String adminPass;

  public static final String JSON_PROPERTY_USER_DATA = "user_data";
  private String userData;

  public static final String JSON_PROPERTY_AVAILABILITY_ZONE = "availability_zone";
  private String availabilityZone;

  public static final String JSON_PROPERTY_CONFIG_DRIVE = "config_drive";
  private Boolean configDrive = false;

  public static final String JSON_PROPERTY_NETWORKS = "networks";
  private List<ServersPostRequestServerNetworksInner> networks;

  public static final String JSON_PROPERTY_PERSONALITY = "personality";
  private List<Object> personality;

  public static final String JSON_PROPERTY_BLOCK_DEVICE_MAPPING_V2 = "block_device_mapping_v2";
  private List<ServersPostRequestServerBlockDeviceMappingV2Inner> blockDeviceMappingV2;

  public static final String JSON_PROPERTY_KEY_NAME = "key_name";
  private String keyName;

  public static final String JSON_PROPERTY_OS_COLON_SCHEDULER_HINTS = "os:scheduler_hints";
  private Map<String, String> osColonSchedulerHints = new HashMap<>();

  /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   */
  public enum OsDCFColonDiskConfigEnum {
    AUTO("AUTO"),
    
    MANUAL("MANUAL");

    private String value;

    OsDCFColonDiskConfigEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OsDCFColonDiskConfigEnum fromValue(String value) {
      for (OsDCFColonDiskConfigEnum b : OsDCFColonDiskConfigEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG = "OS-DCF:diskConfig";
  private OsDCFColonDiskConfigEnum osDCFColonDiskConfig;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_TAGS = "tags";
  private List<String> tags;

  public ServersPostRequestServer() {
  }

  public ServersPostRequestServer name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Имя ВМ
   * @return name
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(String name) {
    this.name = name;
  }


  public ServersPostRequestServer flavorRef(String flavorRef) {
    
    this.flavorRef = flavorRef;
    return this;
  }

   /**
   * Идентификатор шаблона конфигурации ВМ
   * @return flavorRef
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLAVOR_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFlavorRef() {
    return flavorRef;
  }


  @JsonProperty(JSON_PROPERTY_FLAVOR_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlavorRef(String flavorRef) {
    this.flavorRef = flavorRef;
  }


  public ServersPostRequestServer imageRef(String imageRef) {
    
    this.imageRef = imageRef;
    return this;
  }

   /**
   * Идентификатор образа, который будет использоваться для ВМ. Не требуется в случае загрузки с диска. Во всех остальных случаях параметр обязательный
   * @return imageRef
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_IMAGE_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getImageRef() {
    return imageRef;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE_REF)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setImageRef(String imageRef) {
    this.imageRef = imageRef;
  }


  public ServersPostRequestServer securityGroups(List<ServersPostRequestServerSecurityGroupsInner> securityGroups) {
    
    this.securityGroups = securityGroups;
    return this;
  }

  public ServersPostRequestServer addSecurityGroupsItem(ServersPostRequestServerSecurityGroupsInner securityGroupsItem) {
    if (this.securityGroups == null) {
      this.securityGroups = new ArrayList<>();
    }
    this.securityGroups.add(securityGroupsItem);
    return this;
  }

   /**
   * Одна или несколько групп безопасности. Если параметр не задан, на ВМ будет создана группа безопасности &#x60;&#x60;default&#x60;&#x60;. Запрошенные группы безопасности не применяются к уже существующим портам
   * @return securityGroups
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECURITY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ServersPostRequestServerSecurityGroupsInner> getSecurityGroups() {
    return securityGroups;
  }


  @JsonProperty(JSON_PROPERTY_SECURITY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecurityGroups(List<ServersPostRequestServerSecurityGroupsInner> securityGroups) {
    this.securityGroups = securityGroups;
  }


  public ServersPostRequestServer metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public ServersPostRequestServer putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Метаданные ВМ. Пары ключ — значение. Максимальный размер ключа и значения метаданных составляет 255 байт каждый
   * @return metadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public ServersPostRequestServer accessIPv4(String accessIPv4) {
    
    this.accessIPv4 = accessIPv4;
    return this;
  }

   /**
   * IP-адрес версии 4 для доступа к ВМ
   * @return accessIPv4
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessIPv4() {
    return accessIPv4;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessIPv4(String accessIPv4) {
    this.accessIPv4 = accessIPv4;
  }


  public ServersPostRequestServer accessIPv6(String accessIPv6) {
    
    this.accessIPv6 = accessIPv6;
    return this;
  }

   /**
   * IP-адрес версии 6 для доступа к ВМ
   * @return accessIPv6
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessIPv6() {
    return accessIPv6;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessIPv6(String accessIPv6) {
    this.accessIPv6 = accessIPv6;
  }


  public ServersPostRequestServer adminPass(String adminPass) {
    
    this.adminPass = adminPass;
    return this;
  }

   /**
   * Административный пароль ВМ
   * @return adminPass
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADMIN_PASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAdminPass() {
    return adminPass;
  }


  @JsonProperty(JSON_PROPERTY_ADMIN_PASS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAdminPass(String adminPass) {
    this.adminPass = adminPass;
  }


  public ServersPostRequestServer userData(String userData) {
    
    this.userData = userData;
    return this;
  }

   /**
   * Информация о конфигурации или сценарии, которые будут использоваться при запуске. Должно быть закодировано в Base64
   * @return userData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserData() {
    return userData;
  }


  @JsonProperty(JSON_PROPERTY_USER_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserData(String userData) {
    this.userData = userData;
  }


  public ServersPostRequestServer availabilityZone(String availabilityZone) {
    
    this.availabilityZone = availabilityZone;
    return this;
  }

   /**
   * Зона доступности ВМ
   * @return availabilityZone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVAILABILITY_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAvailabilityZone() {
    return availabilityZone;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABILITY_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
  }


  public ServersPostRequestServer configDrive(Boolean configDrive) {
    
    this.configDrive = configDrive;
    return this;
  }

   /**
   * Указывает, надо ли подключать конфигурационный диск. Это устройство, монтируемое к ВМ на этапе запуска. ВМ может читать с него файлы, в том числе метаданные
   * @return configDrive
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIG_DRIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getConfigDrive() {
    return configDrive;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG_DRIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigDrive(Boolean configDrive) {
    this.configDrive = configDrive;
  }


  public ServersPostRequestServer networks(List<ServersPostRequestServerNetworksInner> networks) {
    
    this.networks = networks;
    return this;
  }

  public ServersPostRequestServer addNetworksItem(ServersPostRequestServerNetworksInner networksItem) {
    if (this.networks == null) {
      this.networks = new ArrayList<>();
    }
    this.networks.add(networksItem);
    return this;
  }

   /**
   * Массив &#x60;&#x60;networks&#x60;&#x60;. Обязательный параметр, если в проекте несколько сетей. Если вы не указываете параметр &#x60;&#x60;networks&#x60;&#x60;, ВМ подключается к единственной сети, созданной для текущего проекта
   * @return networks
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NETWORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ServersPostRequestServerNetworksInner> getNetworks() {
    return networks;
  }


  @JsonProperty(JSON_PROPERTY_NETWORKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetworks(List<ServersPostRequestServerNetworksInner> networks) {
    this.networks = networks;
  }


  public ServersPostRequestServer personality(List<Object> personality) {
    
    this.personality = personality;
    return this;
  }

  public ServersPostRequestServer addPersonalityItem(Object personalityItem) {
    if (this.personality == null) {
      this.personality = new ArrayList<>();
    }
    this.personality.add(personalityItem);
    return this;
  }

   /**
   * Путь к файлу и текст содержимого для вставки на ВМ при запуске. Максимальный размер данных пути к файлу составляет 255 байт
   * @return personality
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERSONALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getPersonality() {
    return personality;
  }


  @JsonProperty(JSON_PROPERTY_PERSONALITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPersonality(List<Object> personality) {
    this.personality = personality;
  }


  public ServersPostRequestServer blockDeviceMappingV2(List<ServersPostRequestServerBlockDeviceMappingV2Inner> blockDeviceMappingV2) {
    
    this.blockDeviceMappingV2 = blockDeviceMappingV2;
    return this;
  }

  public ServersPostRequestServer addBlockDeviceMappingV2Item(ServersPostRequestServerBlockDeviceMappingV2Inner blockDeviceMappingV2Item) {
    if (this.blockDeviceMappingV2 == null) {
      this.blockDeviceMappingV2 = new ArrayList<>();
    }
    this.blockDeviceMappingV2.add(blockDeviceMappingV2Item);
    return this;
  }

   /**
   * Включает детальный контроль над сопоставлением блочных устройств для ВМ. Обычно это используется для загрузки серверов с дисков
   * @return blockDeviceMappingV2
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BLOCK_DEVICE_MAPPING_V2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ServersPostRequestServerBlockDeviceMappingV2Inner> getBlockDeviceMappingV2() {
    return blockDeviceMappingV2;
  }


  @JsonProperty(JSON_PROPERTY_BLOCK_DEVICE_MAPPING_V2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockDeviceMappingV2(List<ServersPostRequestServerBlockDeviceMappingV2Inner> blockDeviceMappingV2) {
    this.blockDeviceMappingV2 = blockDeviceMappingV2;
  }


  public ServersPostRequestServer keyName(String keyName) {
    
    this.keyName = keyName;
    return this;
  }

   /**
   * Имя ключевой пары
   * @return keyName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeyName() {
    return keyName;
  }


  @JsonProperty(JSON_PROPERTY_KEY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyName(String keyName) {
    this.keyName = keyName;
  }


  public ServersPostRequestServer osColonSchedulerHints(Map<String, String> osColonSchedulerHints) {
    
    this.osColonSchedulerHints = osColonSchedulerHints;
    return this;
  }

  public ServersPostRequestServer putOsColonSchedulerHintsItem(String key, String osColonSchedulerHintsItem) {
    if (this.osColonSchedulerHints == null) {
      this.osColonSchedulerHints = new HashMap<>();
    }
    this.osColonSchedulerHints.put(key, osColonSchedulerHintsItem);
    return this;
  }

   /**
   * Словарь данных для отправки в планировщик. &#x60;&#x60;OS-SCH-HNT:scheduler_hints&#x60;&#x60; можно также указать в качестве строки
   * @return osColonSchedulerHints
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_COLON_SCHEDULER_HINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getOsColonSchedulerHints() {
    return osColonSchedulerHints;
  }


  @JsonProperty(JSON_PROPERTY_OS_COLON_SCHEDULER_HINTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsColonSchedulerHints(Map<String, String> osColonSchedulerHints) {
    this.osColonSchedulerHints = osColonSchedulerHints;
  }


  public ServersPostRequestServer osDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
    return this;
  }

   /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   * @return osDCFColonDiskConfig
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OsDCFColonDiskConfigEnum getOsDCFColonDiskConfig() {
    return osDCFColonDiskConfig;
  }


  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
  }


  public ServersPostRequestServer description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Описание ВМ
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ServersPostRequestServer tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public ServersPostRequestServer addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Список тегов. Теги имеют следующие ограничения:  - Тег — это Unicode-строка длиной не более 60 символов.  - Тег не может быть пустой строкой.  - Теги чувствительны к регистру.  – Символы &#x60;/&#x60; и &#x60;,&#x60; запрещены в имени тега.  - У каждой ВМ может быть не более 50 тегов.
   * @return tags
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTags() {
    return tags;
  }


  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTags(List<String> tags) {
    this.tags = tags;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersPostRequestServer serversPostRequestServer = (ServersPostRequestServer) o;
    return Objects.equals(this.name, serversPostRequestServer.name) &&
        Objects.equals(this.flavorRef, serversPostRequestServer.flavorRef) &&
        Objects.equals(this.imageRef, serversPostRequestServer.imageRef) &&
        Objects.equals(this.securityGroups, serversPostRequestServer.securityGroups) &&
        Objects.equals(this.metadata, serversPostRequestServer.metadata) &&
        Objects.equals(this.accessIPv4, serversPostRequestServer.accessIPv4) &&
        Objects.equals(this.accessIPv6, serversPostRequestServer.accessIPv6) &&
        Objects.equals(this.adminPass, serversPostRequestServer.adminPass) &&
        Objects.equals(this.userData, serversPostRequestServer.userData) &&
        Objects.equals(this.availabilityZone, serversPostRequestServer.availabilityZone) &&
        Objects.equals(this.configDrive, serversPostRequestServer.configDrive) &&
        Objects.equals(this.networks, serversPostRequestServer.networks) &&
        Objects.equals(this.personality, serversPostRequestServer.personality) &&
        Objects.equals(this.blockDeviceMappingV2, serversPostRequestServer.blockDeviceMappingV2) &&
        Objects.equals(this.keyName, serversPostRequestServer.keyName) &&
        Objects.equals(this.osColonSchedulerHints, serversPostRequestServer.osColonSchedulerHints) &&
        Objects.equals(this.osDCFColonDiskConfig, serversPostRequestServer.osDCFColonDiskConfig) &&
        Objects.equals(this.description, serversPostRequestServer.description) &&
        Objects.equals(this.tags, serversPostRequestServer.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, flavorRef, imageRef, securityGroups, metadata, accessIPv4, accessIPv6, adminPass, userData, availabilityZone, configDrive, networks, personality, blockDeviceMappingV2, keyName, osColonSchedulerHints, osDCFColonDiskConfig, description, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersPostRequestServer {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    flavorRef: ").append(toIndentedString(flavorRef)).append("\n");
    sb.append("    imageRef: ").append(toIndentedString(imageRef)).append("\n");
    sb.append("    securityGroups: ").append(toIndentedString(securityGroups)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    accessIPv4: ").append(toIndentedString(accessIPv4)).append("\n");
    sb.append("    accessIPv6: ").append(toIndentedString(accessIPv6)).append("\n");
    sb.append("    adminPass: ").append(toIndentedString(adminPass)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    availabilityZone: ").append(toIndentedString(availabilityZone)).append("\n");
    sb.append("    configDrive: ").append(toIndentedString(configDrive)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    personality: ").append(toIndentedString(personality)).append("\n");
    sb.append("    blockDeviceMappingV2: ").append(toIndentedString(blockDeviceMappingV2)).append("\n");
    sb.append("    keyName: ").append(toIndentedString(keyName)).append("\n");
    sb.append("    osColonSchedulerHints: ").append(toIndentedString(osColonSchedulerHints)).append("\n");
    sb.append("    osDCFColonDiskConfig: ").append(toIndentedString(osDCFColonDiskConfig)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

