/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetVolumesAttachments;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersServerIdOsVolumeAttachmentsPost200Response
 */
@JsonPropertyOrder({
  ServersServerIdOsVolumeAttachmentsPost200Response.JSON_PROPERTY_VOLUME_ATTACHMENTS
})
@JsonTypeName("_servers__server_id__os_volume_attachments_post_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersServerIdOsVolumeAttachmentsPost200Response {
  public static final String JSON_PROPERTY_VOLUME_ATTACHMENTS = "volumeAttachments";
  private GetVolumesAttachments volumeAttachments;

  public ServersServerIdOsVolumeAttachmentsPost200Response() {
  }

  public ServersServerIdOsVolumeAttachmentsPost200Response volumeAttachments(GetVolumesAttachments volumeAttachments) {
    
    this.volumeAttachments = volumeAttachments;
    return this;
  }

   /**
   * Get volumeAttachments
   * @return volumeAttachments
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VOLUME_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetVolumesAttachments getVolumeAttachments() {
    return volumeAttachments;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_ATTACHMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeAttachments(GetVolumesAttachments volumeAttachments) {
    this.volumeAttachments = volumeAttachments;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersServerIdOsVolumeAttachmentsPost200Response serversServerIdOsVolumeAttachmentsPost200Response = (ServersServerIdOsVolumeAttachmentsPost200Response) o;
    return Objects.equals(this.volumeAttachments, serversServerIdOsVolumeAttachmentsPost200Response.volumeAttachments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volumeAttachments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersServerIdOsVolumeAttachmentsPost200Response {\n");
    sb.append("    volumeAttachments: ").append(toIndentedString(volumeAttachments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

