/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersPostRequestServerNetworksInner
 */
@JsonPropertyOrder({
  ServersPostRequestServerNetworksInner.JSON_PROPERTY_UUID,
  ServersPostRequestServerNetworksInner.JSON_PROPERTY_PORT,
  ServersPostRequestServerNetworksInner.JSON_PROPERTY_FIXED_IP,
  ServersPostRequestServerNetworksInner.JSON_PROPERTY_TAG
})
@JsonTypeName("_servers_post_request_server_networks_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersPostRequestServerNetworksInner {
  public static final String JSON_PROPERTY_UUID = "uuid";
  private String uuid;

  public static final String JSON_PROPERTY_PORT = "port";
  private String port;

  public static final String JSON_PROPERTY_FIXED_IP = "fixed_ip";
  private String fixedIp;

  public static final String JSON_PROPERTY_TAG = "tag";
  private String tag;

  public ServersPostRequestServerNetworksInner() {
  }

  public ServersPostRequestServerNetworksInner uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Идентификатор сети
   * @return uuid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public ServersPostRequestServerNetworksInner port(String port) {
    
    this.port = port;
    return this;
  }

   /**
   * Идентификатор порта
   * @return port
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPort() {
    return port;
  }


  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(String port) {
    this.port = port;
  }


  public ServersPostRequestServerNetworksInner fixedIp(String fixedIp) {
    
    this.fixedIp = fixedIp;
    return this;
  }

   /**
   * Фиксированный адрес IPv4 для сетевого адаптера. Действует для сетей &#x60;&#x60;neutron&#x60;&#x60; или &#x60;&#x60;nova-networks&#x60;&#x60;
   * @return fixedIp
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIXED_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFixedIp() {
    return fixedIp;
  }


  @JsonProperty(JSON_PROPERTY_FIXED_IP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFixedIp(String fixedIp) {
    this.fixedIp = fixedIp;
  }


  public ServersPostRequestServerNetworksInner tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * Тег роли устройства, который можно применить к сетевому интерфейсу
   * @return tag
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTag() {
    return tag;
  }


  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(String tag) {
    this.tag = tag;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersPostRequestServerNetworksInner serversPostRequestServerNetworksInner = (ServersPostRequestServerNetworksInner) o;
    return Objects.equals(this.uuid, serversPostRequestServerNetworksInner.uuid) &&
        Objects.equals(this.port, serversPostRequestServerNetworksInner.port) &&
        Objects.equals(this.fixedIp, serversPostRequestServerNetworksInner.fixedIp) &&
        Objects.equals(this.tag, serversPostRequestServerNetworksInner.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, port, fixedIp, tag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersPostRequestServerNetworksInner {\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    fixedIp: ").append(toIndentedString(fixedIp)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

