/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersPostRequestServerBlockDeviceMappingV2Inner
 */
@JsonPropertyOrder({
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_DEVICE_NAME,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_SOURCE_TYPE,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_DESTINATION_TYPE,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_DELETE_ON_TERMINATION,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_GUEST_FORMAT,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_BOOT_INDEX,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_UUID,
  ServersPostRequestServerBlockDeviceMappingV2Inner.JSON_PROPERTY_TAG
})
@JsonTypeName("_servers_post_request_server_block_device_mapping_v2_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersPostRequestServerBlockDeviceMappingV2Inner {
  public static final String JSON_PROPERTY_DEVICE_NAME = "device_name";
  private String deviceName;

  /**
   * Тип диска
   */
  public enum SourceTypeEnum {
    BLANK("blank"),
    
    SNAPSHOT("snapshot"),
    
    VOLUME("volume"),
    
    IMAGE("image");

    private String value;

    SourceTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceTypeEnum fromValue(String value) {
      for (SourceTypeEnum b : SourceTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE_TYPE = "source_type";
  private SourceTypeEnum sourceType;

  /**
   * Определяет, откуда берется диск
   */
  public enum DestinationTypeEnum {
    LOCAL("local"),
    
    VOLUME("volume");

    private String value;

    DestinationTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DestinationTypeEnum fromValue(String value) {
      for (DestinationTypeEnum b : DestinationTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DESTINATION_TYPE = "destination_type";
  private DestinationTypeEnum destinationType;

  public static final String JSON_PROPERTY_DELETE_ON_TERMINATION = "delete_on_termination";
  private Boolean deleteOnTermination = false;

  /**
   * Формат файловой системы диска гостевого сервера
   */
  public enum GuestFormatEnum {
    EPHEMERAL("ephemeral"),
    
    SWAP("swap");

    private String value;

    GuestFormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static GuestFormatEnum fromValue(String value) {
      for (GuestFormatEnum b : GuestFormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_GUEST_FORMAT = "guest_format";
  private GuestFormatEnum guestFormat;

  public static final String JSON_PROPERTY_BOOT_INDEX = "boot_index";
  private String bootIndex = "None";

  public static final String JSON_PROPERTY_UUID = "uuid";
  private String uuid;

  public static final String JSON_PROPERTY_TAG = "tag";
  private String tag;

  public ServersPostRequestServerBlockDeviceMappingV2Inner() {
  }

  public ServersPostRequestServerBlockDeviceMappingV2Inner deviceName(String deviceName) {
    
    this.deviceName = deviceName;
    return this;
  }

   /**
   * Путь к устройству диска, который вы хотите использовать для загрузки сервера
   * @return deviceName
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getDeviceName() {
    return deviceName;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeviceName(String deviceName) {
    this.deviceName = deviceName;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner sourceType(SourceTypeEnum sourceType) {
    
    this.sourceType = sourceType;
    return this;
  }

   /**
   * Тип диска
   * @return sourceType
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SourceTypeEnum getSourceType() {
    return sourceType;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSourceType(SourceTypeEnum sourceType) {
    this.sourceType = sourceType;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner destinationType(DestinationTypeEnum destinationType) {
    
    this.destinationType = destinationType;
    return this;
  }

   /**
   * Определяет, откуда берется диск
   * @return destinationType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESTINATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DestinationTypeEnum getDestinationType() {
    return destinationType;
  }


  @JsonProperty(JSON_PROPERTY_DESTINATION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDestinationType(DestinationTypeEnum destinationType) {
    this.destinationType = destinationType;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner deleteOnTermination(Boolean deleteOnTermination) {
    
    this.deleteOnTermination = deleteOnTermination;
    return this;
  }

   /**
   * Чтобы удалить загрузочный диск при уничтожении сервера, укажите &#x60;&#x60;true&#x60;&#x60;. В противном случае укажите &#x60;&#x60;false&#x60;&#x60;. По умолчанию: &#x60;&#x60;false&#x60;&#x60;
   * @return deleteOnTermination
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETE_ON_TERMINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDeleteOnTermination() {
    return deleteOnTermination;
  }


  @JsonProperty(JSON_PROPERTY_DELETE_ON_TERMINATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleteOnTermination(Boolean deleteOnTermination) {
    this.deleteOnTermination = deleteOnTermination;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner guestFormat(GuestFormatEnum guestFormat) {
    
    this.guestFormat = guestFormat;
    return this;
  }

   /**
   * Формат файловой системы диска гостевого сервера
   * @return guestFormat
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GUEST_FORMAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GuestFormatEnum getGuestFormat() {
    return guestFormat;
  }


  @JsonProperty(JSON_PROPERTY_GUEST_FORMAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGuestFormat(GuestFormatEnum guestFormat) {
    this.guestFormat = guestFormat;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner bootIndex(String bootIndex) {
    
    this.bootIndex = bootIndex;
    return this;
  }

   /**
   * Порядок загрузки. Задайте каждому устройству уникальный индекс загрузки, начиная с &#x60;&#x60;0&#x60;&#x60;. Чтобы запретить использование устройства для загрузки, установите отрицательное значение или используйте значение &#x60;&#x60;None&#x60;&#x60;. Простой вариант использования: назначить устройству загрузки индекс &#x60;&#x60;0&#x60;&#x60;, а для всех остальных оставить значение по умолчанию — &#x60;&#x60;None&#x60;&#x60;.  Некоторые гипервизоры могут не поддерживать загрузку с нескольких устройств, в этом случае учитываются только устройства с индексом 0. Другие гипервизоры поддерживают загрузку с нескольких устройств, но только если они разных типов (например, диск и CD-ROM).
   * @return bootIndex
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BOOT_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBootIndex() {
    return bootIndex;
  }


  @JsonProperty(JSON_PROPERTY_BOOT_INDEX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBootIndex(String bootIndex) {
    this.bootIndex = bootIndex;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner uuid(String uuid) {
    
    this.uuid = uuid;
    return this;
  }

   /**
   * Идентификатор исходного ресурса. Его значение указывает на разные ресурсы в зависимости от параметра &#x60;&#x60;source_type&#x60;&#x60;. Например, если &#x60;&#x60;source_type&#x60;&#x60; имеет значение &#x60;&#x60;image&#x60;&#x60;, блочное устройство создается на основе указанного образа, полученного из сервиса образов
   * @return uuid
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUuid() {
    return uuid;
  }


  @JsonProperty(JSON_PROPERTY_UUID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  public ServersPostRequestServerBlockDeviceMappingV2Inner tag(String tag) {
    
    this.tag = tag;
    return this;
  }

   /**
   * Тег роли устройства, который можно применить к блочному устройству
   * @return tag
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTag() {
    return tag;
  }


  @JsonProperty(JSON_PROPERTY_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTag(String tag) {
    this.tag = tag;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersPostRequestServerBlockDeviceMappingV2Inner serversPostRequestServerBlockDeviceMappingV2Inner = (ServersPostRequestServerBlockDeviceMappingV2Inner) o;
    return Objects.equals(this.deviceName, serversPostRequestServerBlockDeviceMappingV2Inner.deviceName) &&
        Objects.equals(this.sourceType, serversPostRequestServerBlockDeviceMappingV2Inner.sourceType) &&
        Objects.equals(this.destinationType, serversPostRequestServerBlockDeviceMappingV2Inner.destinationType) &&
        Objects.equals(this.deleteOnTermination, serversPostRequestServerBlockDeviceMappingV2Inner.deleteOnTermination) &&
        Objects.equals(this.guestFormat, serversPostRequestServerBlockDeviceMappingV2Inner.guestFormat) &&
        Objects.equals(this.bootIndex, serversPostRequestServerBlockDeviceMappingV2Inner.bootIndex) &&
        Objects.equals(this.uuid, serversPostRequestServerBlockDeviceMappingV2Inner.uuid) &&
        Objects.equals(this.tag, serversPostRequestServerBlockDeviceMappingV2Inner.tag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceName, sourceType, destinationType, deleteOnTermination, guestFormat, bootIndex, uuid, tag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersPostRequestServerBlockDeviceMappingV2Inner {\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    destinationType: ").append(toIndentedString(destinationType)).append("\n");
    sb.append("    deleteOnTermination: ").append(toIndentedString(deleteOnTermination)).append("\n");
    sb.append("    guestFormat: ").append(toIndentedString(guestFormat)).append("\n");
    sb.append("    bootIndex: ").append(toIndentedString(bootIndex)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

