/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersServerIdOsVolumeAttachmentsPostRequest
 */
@JsonPropertyOrder({
  ServersServerIdOsVolumeAttachmentsPostRequest.JSON_PROPERTY_VOLUME_ATTACHMENT
})
@JsonTypeName("_servers__server_id__os_volume_attachments_post_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersServerIdOsVolumeAttachmentsPostRequest {
  public static final String JSON_PROPERTY_VOLUME_ATTACHMENT = "volumeAttachment";
  private ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment volumeAttachment;

  public ServersServerIdOsVolumeAttachmentsPostRequest() {
  }

  public ServersServerIdOsVolumeAttachmentsPostRequest volumeAttachment(ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment volumeAttachment) {
    
    this.volumeAttachment = volumeAttachment;
    return this;
  }

   /**
   * Get volumeAttachment
   * @return volumeAttachment
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VOLUME_ATTACHMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment getVolumeAttachment() {
    return volumeAttachment;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_ATTACHMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeAttachment(ServersServerIdOsVolumeAttachmentsPostRequestVolumeAttachment volumeAttachment) {
    this.volumeAttachment = volumeAttachment;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersServerIdOsVolumeAttachmentsPostRequest serversServerIdOsVolumeAttachmentsPostRequest = (ServersServerIdOsVolumeAttachmentsPostRequest) o;
    return Objects.equals(this.volumeAttachment, serversServerIdOsVolumeAttachmentsPostRequest.volumeAttachment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volumeAttachment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersServerIdOsVolumeAttachmentsPostRequest {\n");
    sb.append("    volumeAttachment: ").append(toIndentedString(volumeAttachment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

