/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ServerDetailsLinksInner;
import org.openapitools.client.model.ServersPostRequestServerSecurityGroupsInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Детальная информация о ВМ
 */
@JsonPropertyOrder({
  ServerDetails.JSON_PROPERTY_ADDRESSES,
  ServerDetails.JSON_PROPERTY_CREATED,
  ServerDetails.JSON_PROPERTY_FLAVOR,
  ServerDetails.JSON_PROPERTY_HOST_ID,
  ServerDetails.JSON_PROPERTY_ID,
  ServerDetails.JSON_PROPERTY_IMAGE,
  ServerDetails.JSON_PROPERTY_KEY_NAME,
  ServerDetails.JSON_PROPERTY_LINKS,
  ServerDetails.JSON_PROPERTY_METADATA,
  ServerDetails.JSON_PROPERTY_NAME,
  ServerDetails.JSON_PROPERTY_ACCESS_I_PV4,
  ServerDetails.JSON_PROPERTY_ACCESS_I_PV6,
  ServerDetails.JSON_PROPERTY_CONFIG_DRIVE,
  ServerDetails.JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_A_Z_COLON_AVAILABILITY_ZONE,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_POWER_STATE,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_TASK_STATE,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_VM_STATE,
  ServerDetails.JSON_PROPERTY_OS_EXTENDED_VOLUMES_COLON_VOLUMES_ATTACHED,
  ServerDetails.JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_LAUNCHED_AT,
  ServerDetails.JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_TERMINATED_AT,
  ServerDetails.JSON_PROPERTY_PROGRESS,
  ServerDetails.JSON_PROPERTY_SECURITY_GROUPS,
  ServerDetails.JSON_PROPERTY_TENANT_ID,
  ServerDetails.JSON_PROPERTY_UPDATED,
  ServerDetails.JSON_PROPERTY_USER_ID,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_HOSTNAME,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RESERVATION_ID,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_LAUNCH_INDEX,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_KERNEL_ID,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RAMDISK_ID,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_ROOT_DEVICE_NAME,
  ServerDetails.JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_USER_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServerDetails {
  public static final String JSON_PROPERTY_ADDRESSES = "addresses";
  private Object addresses;

  public static final String JSON_PROPERTY_CREATED = "created";
  private String created;

  public static final String JSON_PROPERTY_FLAVOR = "flavor";
  private Object flavor;

  public static final String JSON_PROPERTY_HOST_ID = "hostId";
  private String hostId;

  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_IMAGE = "image";
  private Object image;

  public static final String JSON_PROPERTY_KEY_NAME = "key_name";
  private String keyName;

  public static final String JSON_PROPERTY_LINKS = "links";
  private List<ServerDetailsLinksInner> links;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Map<String, String> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ACCESS_I_PV4 = "accessIPv4";
  private String accessIPv4;

  public static final String JSON_PROPERTY_ACCESS_I_PV6 = "accessIPv6";
  private String accessIPv6;

  public static final String JSON_PROPERTY_CONFIG_DRIVE = "config_drive";
  private Boolean configDrive;

  /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   */
  public enum OsDCFColonDiskConfigEnum {
    AUTO("AUTO"),
    
    MANUAL("MANUAL");

    private String value;

    OsDCFColonDiskConfigEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OsDCFColonDiskConfigEnum fromValue(String value) {
      for (OsDCFColonDiskConfigEnum b : OsDCFColonDiskConfigEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG = "OS-DCF:diskConfig";
  private OsDCFColonDiskConfigEnum osDCFColonDiskConfig;

  public static final String JSON_PROPERTY_OS_E_X_T_A_Z_COLON_AVAILABILITY_ZONE = "OS-EXT-AZ:availability_zone";
  private String osEXTAZColonAvailabilityZone;

  /**
   * Состояние питания ВМ
   */
  public enum OsEXTSTSColonPowerStateEnum {
    NUMBER_0(0),
    
    NUMBER_1(1),
    
    NUMBER_3(3),
    
    NUMBER_4(4),
    
    NUMBER_6(6),
    
    NUMBER_7(7);

    private Integer value;

    OsEXTSTSColonPowerStateEnum(Integer value) {
      this.value = value;
    }

    @JsonValue
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OsEXTSTSColonPowerStateEnum fromValue(Integer value) {
      for (OsEXTSTSColonPowerStateEnum b : OsEXTSTSColonPowerStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_POWER_STATE = "OS-EXT-STS:power_state";
  private OsEXTSTSColonPowerStateEnum osEXTSTSColonPowerState;

  public static final String JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_TASK_STATE = "OS-EXT-STS:task_state";
  private String osEXTSTSColonTaskState;

  public static final String JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_VM_STATE = "OS-EXT-STS:vm_state";
  private String osEXTSTSColonVmState;

  public static final String JSON_PROPERTY_OS_EXTENDED_VOLUMES_COLON_VOLUMES_ATTACHED = "os-extended-volumes:volumes_attached";
  private Object osExtendedVolumesColonVolumesAttached;

  public static final String JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_LAUNCHED_AT = "OS-SRV-USG:launched_at";
  private String osSRVUSGColonLaunchedAt;

  public static final String JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_TERMINATED_AT = "OS-SRV-USG:terminated_at";
  private String osSRVUSGColonTerminatedAt;

  public static final String JSON_PROPERTY_PROGRESS = "progress";
  private Integer progress;

  public static final String JSON_PROPERTY_SECURITY_GROUPS = "security_groups";
  private List<ServersPostRequestServerSecurityGroupsInner> securityGroups;

  public static final String JSON_PROPERTY_TENANT_ID = "tenant_id";
  private String tenantId;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  private String updated;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  private String userId;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_HOSTNAME = "OS-EXT-SERV-ATTR:hostname";
  private String osEXTSERVATTRColonHostname;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RESERVATION_ID = "OS-EXT-SERV-ATTR:reservation_id";
  private String osEXTSERVATTRColonReservationId;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_LAUNCH_INDEX = "OS-EXT-SERV-ATTR:launch_index";
  private Integer osEXTSERVATTRColonLaunchIndex;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_KERNEL_ID = "OS-EXT-SERV-ATTR:kernel_id";
  private String osEXTSERVATTRColonKernelId;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RAMDISK_ID = "OS-EXT-SERV-ATTR:ramdisk_id";
  private String osEXTSERVATTRColonRamdiskId;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_ROOT_DEVICE_NAME = "OS-EXT-SERV-ATTR:root_device_name";
  private String osEXTSERVATTRColonRootDeviceName;

  public static final String JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_USER_DATA = "OS-EXT-SERV-ATTR:user_data";
  private String osEXTSERVATTRColonUserData;

  public ServerDetails() {
  }

  public ServerDetails addresses(Object addresses) {
    
    this.addresses = addresses;
    return this;
  }

   /**
   * Адреса ВМ. Для получения дополнительной информации см. &#x60;&#x60;nova.conf&#x60;&#x60; параметры конфигурации http://docs.openstack.org/liberty/config-reference/content/list-of-compute-config-options.html
   * @return addresses
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getAddresses() {
    return addresses;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddresses(Object addresses) {
    this.addresses = addresses;
  }


  public ServerDetails created(String created) {
    
    this.created = created;
    return this;
  }

   /**
   * Дата и время создания ресурса. Формат: &#x60;&#x60;CCYY-MM-DDThh:mm:ss±hh:mm&#x60;&#x60;. Значение &#x60;&#x60;±hh:mm&#x60;&#x60; указывает на часовой пояс (смещение от UTC)
   * @return created
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(String created) {
    this.created = created;
  }


  public ServerDetails flavor(Object flavor) {
    
    this.flavor = flavor;
    return this;
  }

   /**
   * Идентификатор и ссылки на шаблон конфигурации ВМ
   * @return flavor
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FLAVOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getFlavor() {
    return flavor;
  }


  @JsonProperty(JSON_PROPERTY_FLAVOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlavor(Object flavor) {
    this.flavor = flavor;
  }


  public ServerDetails hostId(String hostId) {
    
    this.hostId = hostId;
    return this;
  }

   /**
   * Идентификатор хоста
   * @return hostId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHostId() {
    return hostId;
  }


  @JsonProperty(JSON_PROPERTY_HOST_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostId(String hostId) {
    this.hostId = hostId;
  }


  public ServerDetails id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Идентификатор ВМ
   * @return id
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public ServerDetails image(Object image) {
    
    this.image = image;
    return this;
  }

   /**
   * Идентификатор и ссылки на образ. Объект может быть пустой при загрузке ВМ с диска
   * @return image
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(Object image) {
    this.image = image;
  }


  public ServerDetails keyName(String keyName) {
    
    this.keyName = keyName;
    return this;
  }

   /**
   * Имя связанной ключевой пары, если есть
   * @return keyName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeyName() {
    return keyName;
  }


  @JsonProperty(JSON_PROPERTY_KEY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeyName(String keyName) {
    this.keyName = keyName;
  }


  public ServerDetails links(List<ServerDetailsLinksInner> links) {
    
    this.links = links;
    return this;
  }

  public ServerDetails addLinksItem(ServerDetailsLinksInner linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Ссылки на рассматриваемые ресурсы. Дополнительная информация — &#x60;http:developer.openstack.org/api-guide/compute/links_and_references.html&#x60;
   * @return links
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ServerDetailsLinksInner> getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(List<ServerDetailsLinksInner> links) {
    this.links = links;
  }


  public ServerDetails metadata(Map<String, String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public ServerDetails putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Метаданные ВМ
   * @return metadata
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }


  public ServerDetails name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Имя ВМ
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ServerDetails accessIPv4(String accessIPv4) {
    
    this.accessIPv4 = accessIPv4;
    return this;
  }

   /**
   * IP-адрес версии 4, который следует использовать для доступа к ВМ
   * @return accessIPv4
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessIPv4() {
    return accessIPv4;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessIPv4(String accessIPv4) {
    this.accessIPv4 = accessIPv4;
  }


  public ServerDetails accessIPv6(String accessIPv6) {
    
    this.accessIPv6 = accessIPv6;
    return this;
  }

   /**
   * IP-адрес версии 6, который следует использовать для доступа к ВМ
   * @return accessIPv6
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessIPv6() {
    return accessIPv6;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessIPv6(String accessIPv6) {
    this.accessIPv6 = accessIPv6;
  }


  public ServerDetails configDrive(Boolean configDrive) {
    
    this.configDrive = configDrive;
    return this;
  }

   /**
   * Указывает, использовался ли для этой ВМ конфигурационный диск
   * @return configDrive
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIG_DRIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getConfigDrive() {
    return configDrive;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG_DRIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfigDrive(Boolean configDrive) {
    this.configDrive = configDrive;
  }


  public ServerDetails osDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
    return this;
  }

   /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   * @return osDCFColonDiskConfig
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OsDCFColonDiskConfigEnum getOsDCFColonDiskConfig() {
    return osDCFColonDiskConfig;
  }


  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
  }


  public ServerDetails osEXTAZColonAvailabilityZone(String osEXTAZColonAvailabilityZone) {
    
    this.osEXTAZColonAvailabilityZone = osEXTAZColonAvailabilityZone;
    return this;
  }

   /**
   * Имя зоны доступности
   * @return osEXTAZColonAvailabilityZone
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_A_Z_COLON_AVAILABILITY_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTAZColonAvailabilityZone() {
    return osEXTAZColonAvailabilityZone;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_A_Z_COLON_AVAILABILITY_ZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTAZColonAvailabilityZone(String osEXTAZColonAvailabilityZone) {
    this.osEXTAZColonAvailabilityZone = osEXTAZColonAvailabilityZone;
  }


  public ServerDetails osEXTSTSColonPowerState(OsEXTSTSColonPowerStateEnum osEXTSTSColonPowerState) {
    
    this.osEXTSTSColonPowerState = osEXTSTSColonPowerState;
    return this;
  }

   /**
   * Состояние питания ВМ
   * @return osEXTSTSColonPowerState
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_POWER_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OsEXTSTSColonPowerStateEnum getOsEXTSTSColonPowerState() {
    return osEXTSTSColonPowerState;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_POWER_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSTSColonPowerState(OsEXTSTSColonPowerStateEnum osEXTSTSColonPowerState) {
    this.osEXTSTSColonPowerState = osEXTSTSColonPowerState;
  }


  public ServerDetails osEXTSTSColonTaskState(String osEXTSTSColonTaskState) {
    
    this.osEXTSTSColonTaskState = osEXTSTSColonTaskState;
    return this;
  }

   /**
   * Состояние задачи ВМ
   * @return osEXTSTSColonTaskState
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_TASK_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSTSColonTaskState() {
    return osEXTSTSColonTaskState;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_TASK_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSTSColonTaskState(String osEXTSTSColonTaskState) {
    this.osEXTSTSColonTaskState = osEXTSTSColonTaskState;
  }


  public ServerDetails osEXTSTSColonVmState(String osEXTSTSColonVmState) {
    
    this.osEXTSTSColonVmState = osEXTSTSColonVmState;
    return this;
  }

   /**
   * Состояние ВМ
   * @return osEXTSTSColonVmState
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_VM_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSTSColonVmState() {
    return osEXTSTSColonVmState;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_T_S_COLON_VM_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSTSColonVmState(String osEXTSTSColonVmState) {
    this.osEXTSTSColonVmState = osEXTSTSColonVmState;
  }


  public ServerDetails osExtendedVolumesColonVolumesAttached(Object osExtendedVolumesColonVolumesAttached) {
    
    this.osExtendedVolumesColonVolumesAttached = osExtendedVolumesColonVolumesAttached;
    return this;
  }

   /**
   * Прикрепленные диски, если есть
   * @return osExtendedVolumesColonVolumesAttached
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_EXTENDED_VOLUMES_COLON_VOLUMES_ATTACHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getOsExtendedVolumesColonVolumesAttached() {
    return osExtendedVolumesColonVolumesAttached;
  }


  @JsonProperty(JSON_PROPERTY_OS_EXTENDED_VOLUMES_COLON_VOLUMES_ATTACHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsExtendedVolumesColonVolumesAttached(Object osExtendedVolumesColonVolumesAttached) {
    this.osExtendedVolumesColonVolumesAttached = osExtendedVolumesColonVolumesAttached;
  }


  public ServerDetails osSRVUSGColonLaunchedAt(String osSRVUSGColonLaunchedAt) {
    
    this.osSRVUSGColonLaunchedAt = osSRVUSGColonLaunchedAt;
    return this;
  }

   /**
   * Дата и время запуска ВМ. Формат: &#x60;&#x60;CCYY-MM-DDThh:mm:ss±hh:mm&#x60;&#x60;. Значение &#x60;&#x60;±hh:mm&#x60;&#x60; указывает на часовой пояс (смещение от UTC)
   * @return osSRVUSGColonLaunchedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_LAUNCHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsSRVUSGColonLaunchedAt() {
    return osSRVUSGColonLaunchedAt;
  }


  @JsonProperty(JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_LAUNCHED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsSRVUSGColonLaunchedAt(String osSRVUSGColonLaunchedAt) {
    this.osSRVUSGColonLaunchedAt = osSRVUSGColonLaunchedAt;
  }


  public ServerDetails osSRVUSGColonTerminatedAt(String osSRVUSGColonTerminatedAt) {
    
    this.osSRVUSGColonTerminatedAt = osSRVUSGColonTerminatedAt;
    return this;
  }

   /**
   * Дата и время удаления ВМ. Формат: &#x60;&#x60;CCYY-MM-DDThh:mm:ss±hh:mm&#x60;&#x60;. Значение &#x60;&#x60;±hh:mm&#x60;&#x60; указывает на часовой пояс (смещение от UTC)
   * @return osSRVUSGColonTerminatedAt
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_TERMINATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsSRVUSGColonTerminatedAt() {
    return osSRVUSGColonTerminatedAt;
  }


  @JsonProperty(JSON_PROPERTY_OS_S_R_V_U_S_G_COLON_TERMINATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsSRVUSGColonTerminatedAt(String osSRVUSGColonTerminatedAt) {
    this.osSRVUSGColonTerminatedAt = osSRVUSGColonTerminatedAt;
  }


  public ServerDetails progress(Integer progress) {
    
    this.progress = progress;
    return this;
  }

   /**
   * Процентное значение прогресса удаления
   * @return progress
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProgress() {
    return progress;
  }


  @JsonProperty(JSON_PROPERTY_PROGRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProgress(Integer progress) {
    this.progress = progress;
  }


  public ServerDetails securityGroups(List<ServersPostRequestServerSecurityGroupsInner> securityGroups) {
    
    this.securityGroups = securityGroups;
    return this;
  }

  public ServerDetails addSecurityGroupsItem(ServersPostRequestServerSecurityGroupsInner securityGroupsItem) {
    if (this.securityGroups == null) {
      this.securityGroups = new ArrayList<>();
    }
    this.securityGroups.add(securityGroupsItem);
    return this;
  }

   /**
   * Группы безопасности
   * @return securityGroups
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECURITY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ServersPostRequestServerSecurityGroupsInner> getSecurityGroups() {
    return securityGroups;
  }


  @JsonProperty(JSON_PROPERTY_SECURITY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecurityGroups(List<ServersPostRequestServerSecurityGroupsInner> securityGroups) {
    this.securityGroups = securityGroups;
  }


  public ServerDetails tenantId(String tenantId) {
    
    this.tenantId = tenantId;
    return this;
  }

   /**
   * Значение параметра &lt;a href&#x3D;&#39;https://cloud.vk.com/docs/tools-for-using-services/api/rest-api/endpoints#poluchenie_project_id&#39;&gt;Project ID&lt;/a&gt; для проекта
   * @return tenantId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTenantId() {
    return tenantId;
  }


  @JsonProperty(JSON_PROPERTY_TENANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }


  public ServerDetails updated(String updated) {
    
    this.updated = updated;
    return this;
  }

   /**
   * Дата и время обновления ресурса. Формат: &#x60;&#x60;CCYY-MM-DDThh:mm:ss±hh:mm&#x60;&#x60;. Значение &#x60;&#x60;±hh:mm&#x60;&#x60; указывает на часовой пояс (смещение от UTC)
   * @return updated
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdated() {
    return updated;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdated(String updated) {
    this.updated = updated;
  }


  public ServerDetails userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Идентификатор пользователя, которому принадлежит ВМ
   * @return userId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }


  public ServerDetails osEXTSERVATTRColonHostname(String osEXTSERVATTRColonHostname) {
    
    this.osEXTSERVATTRColonHostname = osEXTSERVATTRColonHostname;
    return this;
  }

   /**
   * Имя хоста, заданное для ВМ при его загрузке
   * @return osEXTSERVATTRColonHostname
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_HOSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSERVATTRColonHostname() {
    return osEXTSERVATTRColonHostname;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_HOSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonHostname(String osEXTSERVATTRColonHostname) {
    this.osEXTSERVATTRColonHostname = osEXTSERVATTRColonHostname;
  }


  public ServerDetails osEXTSERVATTRColonReservationId(String osEXTSERVATTRColonReservationId) {
    
    this.osEXTSERVATTRColonReservationId = osEXTSERVATTRColonReservationId;
    return this;
  }

   /**
   * Идентификатор резервирования для ВМ. Этот идентификатор может быть полезен при отслеживании групп серверов, созданных множественным вызовом создания ВМ
   * @return osEXTSERVATTRColonReservationId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RESERVATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSERVATTRColonReservationId() {
    return osEXTSERVATTRColonReservationId;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RESERVATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonReservationId(String osEXTSERVATTRColonReservationId) {
    this.osEXTSERVATTRColonReservationId = osEXTSERVATTRColonReservationId;
  }


  public ServerDetails osEXTSERVATTRColonLaunchIndex(Integer osEXTSERVATTRColonLaunchIndex) {
    
    this.osEXTSERVATTRColonLaunchIndex = osEXTSERVATTRColonLaunchIndex;
    return this;
  }

   /**
   * Последовательность запуска ВМ, созданных множественным вызовом создания ВМ
   * @return osEXTSERVATTRColonLaunchIndex
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_LAUNCH_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOsEXTSERVATTRColonLaunchIndex() {
    return osEXTSERVATTRColonLaunchIndex;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_LAUNCH_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonLaunchIndex(Integer osEXTSERVATTRColonLaunchIndex) {
    this.osEXTSERVATTRColonLaunchIndex = osEXTSERVATTRColonLaunchIndex;
  }


  public ServerDetails osEXTSERVATTRColonKernelId(String osEXTSERVATTRColonKernelId) {
    
    this.osEXTSERVATTRColonKernelId = osEXTSERVATTRColonKernelId;
    return this;
  }

   /**
   * Идентификатор образа ядра при использовании AMI
   * @return osEXTSERVATTRColonKernelId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_KERNEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSERVATTRColonKernelId() {
    return osEXTSERVATTRColonKernelId;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_KERNEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonKernelId(String osEXTSERVATTRColonKernelId) {
    this.osEXTSERVATTRColonKernelId = osEXTSERVATTRColonKernelId;
  }


  public ServerDetails osEXTSERVATTRColonRamdiskId(String osEXTSERVATTRColonRamdiskId) {
    
    this.osEXTSERVATTRColonRamdiskId = osEXTSERVATTRColonRamdiskId;
    return this;
  }

   /**
   * Идентификатор образа виртуального диска при использовании AMI
   * @return osEXTSERVATTRColonRamdiskId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RAMDISK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSERVATTRColonRamdiskId() {
    return osEXTSERVATTRColonRamdiskId;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_RAMDISK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonRamdiskId(String osEXTSERVATTRColonRamdiskId) {
    this.osEXTSERVATTRColonRamdiskId = osEXTSERVATTRColonRamdiskId;
  }


  public ServerDetails osEXTSERVATTRColonRootDeviceName(String osEXTSERVATTRColonRootDeviceName) {
    
    this.osEXTSERVATTRColonRootDeviceName = osEXTSERVATTRColonRootDeviceName;
    return this;
  }

   /**
   * Имя корневого устройства для ВМ
   * @return osEXTSERVATTRColonRootDeviceName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_ROOT_DEVICE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSERVATTRColonRootDeviceName() {
    return osEXTSERVATTRColonRootDeviceName;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_ROOT_DEVICE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonRootDeviceName(String osEXTSERVATTRColonRootDeviceName) {
    this.osEXTSERVATTRColonRootDeviceName = osEXTSERVATTRColonRootDeviceName;
  }


  public ServerDetails osEXTSERVATTRColonUserData(String osEXTSERVATTRColonUserData) {
    
    this.osEXTSERVATTRColonUserData = osEXTSERVATTRColonUserData;
    return this;
  }

   /**
   * Пользовательские данные, с которыми была создана ВМ
   * @return osEXTSERVATTRColonUserData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_USER_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOsEXTSERVATTRColonUserData() {
    return osEXTSERVATTRColonUserData;
  }


  @JsonProperty(JSON_PROPERTY_OS_E_X_T_S_E_R_V_A_T_T_R_COLON_USER_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsEXTSERVATTRColonUserData(String osEXTSERVATTRColonUserData) {
    this.osEXTSERVATTRColonUserData = osEXTSERVATTRColonUserData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerDetails serverDetails = (ServerDetails) o;
    return Objects.equals(this.addresses, serverDetails.addresses) &&
        Objects.equals(this.created, serverDetails.created) &&
        Objects.equals(this.flavor, serverDetails.flavor) &&
        Objects.equals(this.hostId, serverDetails.hostId) &&
        Objects.equals(this.id, serverDetails.id) &&
        Objects.equals(this.image, serverDetails.image) &&
        Objects.equals(this.keyName, serverDetails.keyName) &&
        Objects.equals(this.links, serverDetails.links) &&
        Objects.equals(this.metadata, serverDetails.metadata) &&
        Objects.equals(this.name, serverDetails.name) &&
        Objects.equals(this.accessIPv4, serverDetails.accessIPv4) &&
        Objects.equals(this.accessIPv6, serverDetails.accessIPv6) &&
        Objects.equals(this.configDrive, serverDetails.configDrive) &&
        Objects.equals(this.osDCFColonDiskConfig, serverDetails.osDCFColonDiskConfig) &&
        Objects.equals(this.osEXTAZColonAvailabilityZone, serverDetails.osEXTAZColonAvailabilityZone) &&
        Objects.equals(this.osEXTSTSColonPowerState, serverDetails.osEXTSTSColonPowerState) &&
        Objects.equals(this.osEXTSTSColonTaskState, serverDetails.osEXTSTSColonTaskState) &&
        Objects.equals(this.osEXTSTSColonVmState, serverDetails.osEXTSTSColonVmState) &&
        Objects.equals(this.osExtendedVolumesColonVolumesAttached, serverDetails.osExtendedVolumesColonVolumesAttached) &&
        Objects.equals(this.osSRVUSGColonLaunchedAt, serverDetails.osSRVUSGColonLaunchedAt) &&
        Objects.equals(this.osSRVUSGColonTerminatedAt, serverDetails.osSRVUSGColonTerminatedAt) &&
        Objects.equals(this.progress, serverDetails.progress) &&
        Objects.equals(this.securityGroups, serverDetails.securityGroups) &&
        Objects.equals(this.tenantId, serverDetails.tenantId) &&
        Objects.equals(this.updated, serverDetails.updated) &&
        Objects.equals(this.userId, serverDetails.userId) &&
        Objects.equals(this.osEXTSERVATTRColonHostname, serverDetails.osEXTSERVATTRColonHostname) &&
        Objects.equals(this.osEXTSERVATTRColonReservationId, serverDetails.osEXTSERVATTRColonReservationId) &&
        Objects.equals(this.osEXTSERVATTRColonLaunchIndex, serverDetails.osEXTSERVATTRColonLaunchIndex) &&
        Objects.equals(this.osEXTSERVATTRColonKernelId, serverDetails.osEXTSERVATTRColonKernelId) &&
        Objects.equals(this.osEXTSERVATTRColonRamdiskId, serverDetails.osEXTSERVATTRColonRamdiskId) &&
        Objects.equals(this.osEXTSERVATTRColonRootDeviceName, serverDetails.osEXTSERVATTRColonRootDeviceName) &&
        Objects.equals(this.osEXTSERVATTRColonUserData, serverDetails.osEXTSERVATTRColonUserData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, created, flavor, hostId, id, image, keyName, links, metadata, name, accessIPv4, accessIPv6, configDrive, osDCFColonDiskConfig, osEXTAZColonAvailabilityZone, osEXTSTSColonPowerState, osEXTSTSColonTaskState, osEXTSTSColonVmState, osExtendedVolumesColonVolumesAttached, osSRVUSGColonLaunchedAt, osSRVUSGColonTerminatedAt, progress, securityGroups, tenantId, updated, userId, osEXTSERVATTRColonHostname, osEXTSERVATTRColonReservationId, osEXTSERVATTRColonLaunchIndex, osEXTSERVATTRColonKernelId, osEXTSERVATTRColonRamdiskId, osEXTSERVATTRColonRootDeviceName, osEXTSERVATTRColonUserData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerDetails {\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    flavor: ").append(toIndentedString(flavor)).append("\n");
    sb.append("    hostId: ").append(toIndentedString(hostId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    keyName: ").append(toIndentedString(keyName)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accessIPv4: ").append(toIndentedString(accessIPv4)).append("\n");
    sb.append("    accessIPv6: ").append(toIndentedString(accessIPv6)).append("\n");
    sb.append("    configDrive: ").append(toIndentedString(configDrive)).append("\n");
    sb.append("    osDCFColonDiskConfig: ").append(toIndentedString(osDCFColonDiskConfig)).append("\n");
    sb.append("    osEXTAZColonAvailabilityZone: ").append(toIndentedString(osEXTAZColonAvailabilityZone)).append("\n");
    sb.append("    osEXTSTSColonPowerState: ").append(toIndentedString(osEXTSTSColonPowerState)).append("\n");
    sb.append("    osEXTSTSColonTaskState: ").append(toIndentedString(osEXTSTSColonTaskState)).append("\n");
    sb.append("    osEXTSTSColonVmState: ").append(toIndentedString(osEXTSTSColonVmState)).append("\n");
    sb.append("    osExtendedVolumesColonVolumesAttached: ").append(toIndentedString(osExtendedVolumesColonVolumesAttached)).append("\n");
    sb.append("    osSRVUSGColonLaunchedAt: ").append(toIndentedString(osSRVUSGColonLaunchedAt)).append("\n");
    sb.append("    osSRVUSGColonTerminatedAt: ").append(toIndentedString(osSRVUSGColonTerminatedAt)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    securityGroups: ").append(toIndentedString(securityGroups)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    osEXTSERVATTRColonHostname: ").append(toIndentedString(osEXTSERVATTRColonHostname)).append("\n");
    sb.append("    osEXTSERVATTRColonReservationId: ").append(toIndentedString(osEXTSERVATTRColonReservationId)).append("\n");
    sb.append("    osEXTSERVATTRColonLaunchIndex: ").append(toIndentedString(osEXTSERVATTRColonLaunchIndex)).append("\n");
    sb.append("    osEXTSERVATTRColonKernelId: ").append(toIndentedString(osEXTSERVATTRColonKernelId)).append("\n");
    sb.append("    osEXTSERVATTRColonRamdiskId: ").append(toIndentedString(osEXTSERVATTRColonRamdiskId)).append("\n");
    sb.append("    osEXTSERVATTRColonRootDeviceName: ").append(toIndentedString(osEXTSERVATTRColonRootDeviceName)).append("\n");
    sb.append("    osEXTSERVATTRColonUserData: ").append(toIndentedString(osEXTSERVATTRColonUserData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

