/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetServerSecurityGroups;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServersServerIdOsSecurityGroupsGet200Response
 */
@JsonPropertyOrder({
  ServersServerIdOsSecurityGroupsGet200Response.JSON_PROPERTY_SECURITY_GROUPS
})
@JsonTypeName("_servers__server_id__os_security_groups_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServersServerIdOsSecurityGroupsGet200Response {
  public static final String JSON_PROPERTY_SECURITY_GROUPS = "security_groups";
  private List<GetServerSecurityGroups> securityGroups;

  public ServersServerIdOsSecurityGroupsGet200Response() {
  }

  public ServersServerIdOsSecurityGroupsGet200Response securityGroups(List<GetServerSecurityGroups> securityGroups) {
    
    this.securityGroups = securityGroups;
    return this;
  }

  public ServersServerIdOsSecurityGroupsGet200Response addSecurityGroupsItem(GetServerSecurityGroups securityGroupsItem) {
    if (this.securityGroups == null) {
      this.securityGroups = new ArrayList<>();
    }
    this.securityGroups.add(securityGroupsItem);
    return this;
  }

   /**
   * Get securityGroups
   * @return securityGroups
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECURITY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<GetServerSecurityGroups> getSecurityGroups() {
    return securityGroups;
  }


  @JsonProperty(JSON_PROPERTY_SECURITY_GROUPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecurityGroups(List<GetServerSecurityGroups> securityGroups) {
    this.securityGroups = securityGroups;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServersServerIdOsSecurityGroupsGet200Response serversServerIdOsSecurityGroupsGet200Response = (ServersServerIdOsSecurityGroupsGet200Response) o;
    return Objects.equals(this.securityGroups, serversServerIdOsSecurityGroupsGet200Response.securityGroups);
  }

  @Override
  public int hashCode() {
    return Objects.hash(securityGroups);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServersServerIdOsSecurityGroupsGet200Response {\n");
    sb.append("    securityGroups: ").append(toIndentedString(securityGroups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

