/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ServerUpdateServer
 */
@JsonPropertyOrder({
  ServerUpdateServer.JSON_PROPERTY_NAME,
  ServerUpdateServer.JSON_PROPERTY_DESCRIPTION,
  ServerUpdateServer.JSON_PROPERTY_ACCESS_I_PV4,
  ServerUpdateServer.JSON_PROPERTY_ACCESS_I_PV6,
  ServerUpdateServer.JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG
})
@JsonTypeName("ServerUpdate_server")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class ServerUpdateServer {
  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_ACCESS_I_PV4 = "accessIPv4";
  private String accessIPv4;

  public static final String JSON_PROPERTY_ACCESS_I_PV6 = "accessIPv6";
  private String accessIPv6;

  /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   */
  public enum OsDCFColonDiskConfigEnum {
    AUTO("AUTO"),
    
    MANUAL("MANUAL");

    private String value;

    OsDCFColonDiskConfigEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OsDCFColonDiskConfigEnum fromValue(String value) {
      for (OsDCFColonDiskConfigEnum b : OsDCFColonDiskConfigEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG = "OS-DCF:diskConfig";
  private OsDCFColonDiskConfigEnum osDCFColonDiskConfig;

  public ServerUpdateServer() {
  }

  public ServerUpdateServer name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Новое имя ВМ
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public ServerUpdateServer description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Новое описание ВМ
   * @return description
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public ServerUpdateServer accessIPv4(String accessIPv4) {
    
    this.accessIPv4 = accessIPv4;
    return this;
  }

   /**
   * Новый IP-адрес версии 4, который следует использовать для доступа к ВМ
   * @return accessIPv4
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessIPv4() {
    return accessIPv4;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV4)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessIPv4(String accessIPv4) {
    this.accessIPv4 = accessIPv4;
  }


  public ServerUpdateServer accessIPv6(String accessIPv6) {
    
    this.accessIPv6 = accessIPv6;
    return this;
  }

   /**
   * Новый IP-адрес версии 6, который следует использовать для доступа к ВМ
   * @return accessIPv6
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccessIPv6() {
    return accessIPv6;
  }


  @JsonProperty(JSON_PROPERTY_ACCESS_I_PV6)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessIPv6(String accessIPv6) {
    this.accessIPv6 = accessIPv6;
  }


  public ServerUpdateServer osDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
    return this;
  }

   /**
   * Конфигурация диска. Возможные значения:  &#x60;&#x60;AUTO&#x60;&#x60; — будет создана ВМ с одним разделом, размером с целевой диск. Файловая система автоматически настраивается, чтобы соответствовать всему разделу.  &#x60;&#x60;MANUAL&#x60;&#x60; — ВМ будет создана с использованием схемы разделов и файловую систему, которая находится в исходном образе, если целевой диск больше. Оставшееся дисковое пространство не будет разделено
   * @return osDCFColonDiskConfig
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OsDCFColonDiskConfigEnum getOsDCFColonDiskConfig() {
    return osDCFColonDiskConfig;
  }


  @JsonProperty(JSON_PROPERTY_OS_D_C_F_COLON_DISK_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsDCFColonDiskConfig(OsDCFColonDiskConfigEnum osDCFColonDiskConfig) {
    this.osDCFColonDiskConfig = osDCFColonDiskConfig;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerUpdateServer serverUpdateServer = (ServerUpdateServer) o;
    return Objects.equals(this.name, serverUpdateServer.name) &&
        Objects.equals(this.description, serverUpdateServer.description) &&
        Objects.equals(this.accessIPv4, serverUpdateServer.accessIPv4) &&
        Objects.equals(this.accessIPv6, serverUpdateServer.accessIPv6) &&
        Objects.equals(this.osDCFColonDiskConfig, serverUpdateServer.osDCFColonDiskConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, accessIPv4, accessIPv6, osDCFColonDiskConfig);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerUpdateServer {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    accessIPv4: ").append(toIndentedString(accessIPv4)).append("\n");
    sb.append("    accessIPv6: ").append(toIndentedString(accessIPv6)).append("\n");
    sb.append("    osDCFColonDiskConfig: ").append(toIndentedString(osDCFColonDiskConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

