/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Одиночная запись о версии
 */
@JsonPropertyOrder({
  Version.JSON_PROPERTY_ID,
  Version.JSON_PROPERTY_LINKS,
  Version.JSON_PROPERTY_STATUS,
  Version.JSON_PROPERTY_VERSION,
  Version.JSON_PROPERTY_MIN_VERSION,
  Version.JSON_PROPERTY_UPDATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-24T15:32:07.370943+03:00[Europe/Moscow]", comments = "Generator version: 7.4.0")
public class Version {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_LINKS = "links";
  private List<Map<String, String>> links = new ArrayList<>();

  /**
   * Статус версии
   */
  public enum StatusEnum {
    CURRENT("CURRENT"),
    
    SUPPORTED("SUPPORTED"),
    
    DEPRECATED("DEPRECATED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public static final String JSON_PROPERTY_VERSION = "version";
  private String version;

  public static final String JSON_PROPERTY_MIN_VERSION = "min_version";
  private String minVersion;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  private String updated;

  public Version() {
  }

  public Version id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Имя версии. Не имеет реального семантического значения
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public Version links(List<Map<String, String>> links) {
    
    this.links = links;
    return this;
  }

  public Version addLinksItem(Map<String, String> linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * Ссылки на рассматриваемые ресурсы. Дополнительная информация — &#x60;http:developer.openstack.org/api-guide/compute/links_and_references.html&#x60;
   * @return links
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Map<String, String>> getLinks() {
    return links;
  }


  @JsonProperty(JSON_PROPERTY_LINKS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLinks(List<Map<String, String>> links) {
    this.links = links;
  }


  public Version status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Статус версии
   * @return status
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  public Version version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Если эта версия API поддерживает микроверсии, максимальная поддерживаемая микроверсия. Если микроверсии не поддерживаются, пустая строка
   * @return version
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVersion() {
    return version;
  }


  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(String version) {
    this.version = version;
  }


  public Version minVersion(String minVersion) {
    
    this.minVersion = minVersion;
    return this;
  }

   /**
   * Если эта версия API поддерживает микроверсии, минимальная поддерживаемая микроверсия. Если микроверсии не поддерживаются, пустая строка
   * @return minVersion
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MIN_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMinVersion() {
    return minVersion;
  }


  @JsonProperty(JSON_PROPERTY_MIN_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMinVersion(String minVersion) {
    this.minVersion = minVersion;
  }


  public Version updated(String updated) {
    
    this.updated = updated;
    return this;
  }

   /**
   * Дата и время обновления
   * @return updated
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getUpdated() {
    return updated;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdated(String updated) {
    this.updated = updated;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Version version = (Version) o;
    return Objects.equals(this.id, version.id) &&
        Objects.equals(this.links, version.links) &&
        Objects.equals(this.status, version.status) &&
        Objects.equals(this.version, version.version) &&
        Objects.equals(this.minVersion, version.minVersion) &&
        Objects.equals(this.updated, version.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, links, status, version, minVersion, updated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Version {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    minVersion: ").append(toIndentedString(minVersion)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

