/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ResultType
 */
public class ResultTypeTest {
    /**
     * Model tests for ResultType
     */
    @Test
    public void testResultType() {
        // TODO: test ResultType
    }

}
