/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.ErrorBadRequest;
import org.openapitools.client.model.GetInstantQueryResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for InstantApi
 */
@Ignore
public class InstantApiTest {

    private final InstantApi api = new InstantApi();

    
    /**
     * Получить метрики в момент времени (Instant query)
     *
     * Выполнить запрос значений метрик для заданного момента времени
     */
    @Test
    public void instantQueryTest()  {
        String projectId = null;
        String query = null;
        String namespace = null;
        String time = null;
        String step = null;
        GetInstantQueryResponse response = api.instantQuery(projectId, query, namespace, time, step).block();

        // TODO: test validations
    }
    
}
