/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.ErrorBadRequest;
import org.openapitools.client.model.GetLabelValuesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for LabelvaluesApi
 */
@Ignore
public class LabelvaluesApiTest {

    private final LabelvaluesApi api = new LabelvaluesApi();

    
    /**
     * Получить значения метки с заданным именем
     *
     * Получить значения метки с заданным именем. В качестве параметров могут быть указаны селекторы метрик и/или диапазон времени, из которых нужно читать значения метки
     */
    @Test
    public void labelValuesTest()  {
        String projectId = null;
        String labelName = null;
        String namespace = null;
        List<String> match = null;
        String start = null;
        String end = null;
        GetLabelValuesResponse response = api.labelValues(projectId, labelName, namespace, match, start, end).block();

        // TODO: test validations
    }
    
}
