/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.ErrorBadRequest;
import org.openapitools.client.model.GetLabelsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for LabelsApi
 */
@Ignore
public class LabelsApiTest {

    private final LabelsApi api = new LabelsApi();

    
    /**
     * Получить список имен меток
     *
     * Получить список имен меток. В качестве параметров могут быть указаны селекторы метрик и/или диапазон времени, из которых нужно читать имена меток
     */
    @Test
    public void labelsTest()  {
        String projectId = null;
        String namespace = null;
        List<String> match = null;
        String start = null;
        String end = null;
        GetLabelsResponse response = api.labels(projectId, namespace, match, start, end).block();

        // TODO: test validations
    }
    
}
