/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for NamespacesApi
 */
@Ignore
public class NamespacesApiTest {

    private final NamespacesApi api = new NamespacesApi();

    
    /**
     * Получить список разрешенных пространств имен
     *
     * Получить список [пространств имен](https://cloud.vk.com/docs/ru/monitoring-services/monitoring/concepts/architecture/#namespaces) (namespaces), которые можно использовать в запросах
     */
    @Test
    public void allowedNamespacesTest()  {
        List<String> response = api.allowedNamespaces().block();

        // TODO: test validations
    }
    
}
