/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.ErrorBadRequest;
import org.openapitools.client.model.GetRangeQueryResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for RangequeryApi
 */
@Ignore
public class RangequeryApiTest {

    private final RangequeryApi api = new RangequeryApi();

    
    /**
     * Получить метрики в диапазоне времени (Range query)
     *
     * Выполнить запрос значений метрик в заданном диапазоне времени
     */
    @Test
    public void rangeQueryTest()  {
        String projectId = null;
        String query = null;
        String start = null;
        String end = null;
        String namespace = null;
        String step = null;
        String timeout = null;
        GetRangeQueryResponse response = api.rangeQuery(projectId, query, start, end, namespace, step, timeout).block();

        // TODO: test validations
    }
    
}
