/*
 * Metrics API
 * Спецификация API для чтения метрик Cloud Monitoring
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Error;
import org.openapitools.client.model.ErrorBadRequest;
import org.openapitools.client.model.GetSeriesQueryResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for SeriesApi
 */
@Ignore
public class SeriesApiTest {

    private final SeriesApi api = new SeriesApi();

    
    /**
     * Получить список метрик по заданному фильтру (Series query)
     *
     * Выполнить запрос списка метрик, которые [соответствуют заданному фильтру](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers). Фильтр задается набором меток в виде пар имя/значение
     */
    @Test
    public void seriesQueryTest()  {
        String projectId = null;
        List<String> match = null;
        String namespace = null;
        String start = null;
        String end = null;
        GetSeriesQueryResponse response = api.seriesQuery(projectId, match, namespace, start, end).block();

        // TODO: test validations
    }
    
}
