/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ChangePassword
 */
public class ChangePasswordTest {
    private final ChangePassword model = new ChangePassword();

    /**
     * Model tests for ChangePassword
     */
    @Test
    public void testChangePassword() {
        // TODO: test ChangePassword
    }

    /**
     * Test the property 'adminPass'
     */
    @Test
    public void adminPassTest() {
        // TODO: test adminPass
    }

}
