/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for FlavorDetails
 */
public class FlavorDetailsTest {
    private final FlavorDetails model = new FlavorDetails();

    /**
     * Model tests for FlavorDetails
     */
    @Test
    public void testFlavorDetails() {
        // TODO: test FlavorDetails
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ram'
     */
    @Test
    public void ramTest() {
        // TODO: test ram
    }

    /**
     * Test the property 'disk'
     */
    @Test
    public void diskTest() {
        // TODO: test disk
    }

    /**
     * Test the property 'vcpus'
     */
    @Test
    public void vcpusTest() {
        // TODO: test vcpus
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'osFLVEXTDATAColonEphemeral'
     */
    @Test
    public void osFLVEXTDATAColonEphemeralTest() {
        // TODO: test osFLVEXTDATAColonEphemeral
    }

    /**
     * Test the property 'swap'
     */
    @Test
    public void swapTest() {
        // TODO: test swap
    }

    /**
     * Test the property 'rxtxFactor'
     */
    @Test
    public void rxtxFactorTest() {
        // TODO: test rxtxFactor
    }

    /**
     * Test the property 'osFlavorAccessColonIsPublic'
     */
    @Test
    public void osFlavorAccessColonIsPublicTest() {
        // TODO: test osFlavorAccessColonIsPublic
    }

    /**
     * Test the property 'extraSpecs'
     */
    @Test
    public void extraSpecsTest() {
        // TODO: test extraSpecs
    }

}
