/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetAvailabilityZoneZoneState;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GetAvailabilityZone
 */
public class GetAvailabilityZoneTest {
    private final GetAvailabilityZone model = new GetAvailabilityZone();

    /**
     * Model tests for GetAvailabilityZone
     */
    @Test
    public void testGetAvailabilityZone() {
        // TODO: test GetAvailabilityZone
    }

    /**
     * Test the property 'hosts'
     */
    @Test
    public void hostsTest() {
        // TODO: test hosts
    }

    /**
     * Test the property 'zoneName'
     */
    @Test
    public void zoneNameTest() {
        // TODO: test zoneName
    }

    /**
     * Test the property 'zoneState'
     */
    @Test
    public void zoneStateTest() {
        // TODO: test zoneState
    }

}
