/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetFlavorsFlavorsInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for GetFlavors
 */
public class GetFlavorsTest {
    private final GetFlavors model = new GetFlavors();

    /**
     * Model tests for GetFlavors
     */
    @Test
    public void testGetFlavors() {
        // TODO: test GetFlavors
    }

    /**
     * Test the property 'flavors'
     */
    @Test
    public void flavorsTest() {
        // TODO: test flavors
    }

}
