/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetKeypairs;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for OsKeypairsKeypairNameGet200Response
 */
public class OsKeypairsKeypairNameGet200ResponseTest {
    private final OsKeypairsKeypairNameGet200Response model = new OsKeypairsKeypairNameGet200Response();

    /**
     * Model tests for OsKeypairsKeypairNameGet200Response
     */
    @Test
    public void testOsKeypairsKeypairNameGet200Response() {
        // TODO: test OsKeypairsKeypairNameGet200Response
    }

    /**
     * Test the property 'keypair'
     */
    @Test
    public void keypairTest() {
        // TODO: test keypair
    }

}
