/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.OsKeypairsPostRequestKeypair;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for OsKeypairsPostRequest
 */
public class OsKeypairsPostRequestTest {
    private final OsKeypairsPostRequest model = new OsKeypairsPostRequest();

    /**
     * Model tests for OsKeypairsPostRequest
     */
    @Test
    public void testOsKeypairsPostRequest() {
        // TODO: test OsKeypairsPostRequest
    }

    /**
     * Test the property 'keypair'
     */
    @Test
    public void keypairTest() {
        // TODO: test keypair
    }

}
