/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.GetServerGroups;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for OsServerGroupsPost200Response
 */
public class OsServerGroupsPost200ResponseTest {
    private final OsServerGroupsPost200Response model = new OsServerGroupsPost200Response();

    /**
     * Model tests for OsServerGroupsPost200Response
     */
    @Test
    public void testOsServerGroupsPost200Response() {
        // TODO: test OsServerGroupsPost200Response
    }

    /**
     * Test the property 'serverGroup'
     */
    @Test
    public void serverGroupTest() {
        // TODO: test serverGroup
    }

}
