/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServersPostRequestServerSecurityGroupsInner
 */
public class ServersPostRequestServerSecurityGroupsInnerTest {
    private final ServersPostRequestServerSecurityGroupsInner model = new ServersPostRequestServerSecurityGroupsInner();

    /**
     * Model tests for ServersPostRequestServerSecurityGroupsInner
     */
    @Test
    public void testServersPostRequestServerSecurityGroupsInner() {
        // TODO: test ServersPostRequestServerSecurityGroupsInner
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
