/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ServersPostRequestServerBlockDeviceMappingV2Inner;
import org.openapitools.client.model.ServersPostRequestServerNetworksInner;
import org.openapitools.client.model.ServersPostRequestServerSecurityGroupsInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServersPostRequestServer
 */
public class ServersPostRequestServerTest {
    private final ServersPostRequestServer model = new ServersPostRequestServer();

    /**
     * Model tests for ServersPostRequestServer
     */
    @Test
    public void testServersPostRequestServer() {
        // TODO: test ServersPostRequestServer
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'flavorRef'
     */
    @Test
    public void flavorRefTest() {
        // TODO: test flavorRef
    }

    /**
     * Test the property 'imageRef'
     */
    @Test
    public void imageRefTest() {
        // TODO: test imageRef
    }

    /**
     * Test the property 'securityGroups'
     */
    @Test
    public void securityGroupsTest() {
        // TODO: test securityGroups
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'accessIPv4'
     */
    @Test
    public void accessIPv4Test() {
        // TODO: test accessIPv4
    }

    /**
     * Test the property 'accessIPv6'
     */
    @Test
    public void accessIPv6Test() {
        // TODO: test accessIPv6
    }

    /**
     * Test the property 'adminPass'
     */
    @Test
    public void adminPassTest() {
        // TODO: test adminPass
    }

    /**
     * Test the property 'userData'
     */
    @Test
    public void userDataTest() {
        // TODO: test userData
    }

    /**
     * Test the property 'availabilityZone'
     */
    @Test
    public void availabilityZoneTest() {
        // TODO: test availabilityZone
    }

    /**
     * Test the property 'configDrive'
     */
    @Test
    public void configDriveTest() {
        // TODO: test configDrive
    }

    /**
     * Test the property 'networks'
     */
    @Test
    public void networksTest() {
        // TODO: test networks
    }

    /**
     * Test the property 'personality'
     */
    @Test
    public void personalityTest() {
        // TODO: test personality
    }

    /**
     * Test the property 'blockDeviceMappingV2'
     */
    @Test
    public void blockDeviceMappingV2Test() {
        // TODO: test blockDeviceMappingV2
    }

    /**
     * Test the property 'keyName'
     */
    @Test
    public void keyNameTest() {
        // TODO: test keyName
    }

    /**
     * Test the property 'osColonSchedulerHints'
     */
    @Test
    public void osColonSchedulerHintsTest() {
        // TODO: test osColonSchedulerHints
    }

    /**
     * Test the property 'osDCFColonDiskConfig'
     */
    @Test
    public void osDCFColonDiskConfigTest() {
        // TODO: test osDCFColonDiskConfig
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
