/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServersPostRequestServerBlockDeviceMappingV2Inner
 */
public class ServersPostRequestServerBlockDeviceMappingV2InnerTest {
    private final ServersPostRequestServerBlockDeviceMappingV2Inner model = new ServersPostRequestServerBlockDeviceMappingV2Inner();

    /**
     * Model tests for ServersPostRequestServerBlockDeviceMappingV2Inner
     */
    @Test
    public void testServersPostRequestServerBlockDeviceMappingV2Inner() {
        // TODO: test ServersPostRequestServerBlockDeviceMappingV2Inner
    }

    /**
     * Test the property 'deviceName'
     */
    @Test
    public void deviceNameTest() {
        // TODO: test deviceName
    }

    /**
     * Test the property 'sourceType'
     */
    @Test
    public void sourceTypeTest() {
        // TODO: test sourceType
    }

    /**
     * Test the property 'destinationType'
     */
    @Test
    public void destinationTypeTest() {
        // TODO: test destinationType
    }

    /**
     * Test the property 'deleteOnTermination'
     */
    @Test
    public void deleteOnTerminationTest() {
        // TODO: test deleteOnTermination
    }

    /**
     * Test the property 'guestFormat'
     */
    @Test
    public void guestFormatTest() {
        // TODO: test guestFormat
    }

    /**
     * Test the property 'bootIndex'
     */
    @Test
    public void bootIndexTest() {
        // TODO: test bootIndex
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

}
