/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServerUpdateServer
 */
public class ServerUpdateServerTest {
    private final ServerUpdateServer model = new ServerUpdateServer();

    /**
     * Model tests for ServerUpdateServer
     */
    @Test
    public void testServerUpdateServer() {
        // TODO: test ServerUpdateServer
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'accessIPv4'
     */
    @Test
    public void accessIPv4Test() {
        // TODO: test accessIPv4
    }

    /**
     * Test the property 'accessIPv6'
     */
    @Test
    public void accessIPv6Test() {
        // TODO: test accessIPv6
    }

    /**
     * Test the property 'osDCFColonDiskConfig'
     */
    @Test
    public void osDCFColonDiskConfigTest() {
        // TODO: test osDCFColonDiskConfig
    }

}
