/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServersPostRequestServerNetworksInner
 */
public class ServersPostRequestServerNetworksInnerTest {
    private final ServersPostRequestServerNetworksInner model = new ServersPostRequestServerNetworksInner();

    /**
     * Model tests for ServersPostRequestServerNetworksInner
     */
    @Test
    public void testServersPostRequestServerNetworksInner() {
        // TODO: test ServersPostRequestServerNetworksInner
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    public void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'fixedIp'
     */
    @Test
    public void fixedIpTest() {
        // TODO: test fixedIp
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

}
