/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetServerSecurityGroups;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServersServerIdOsSecurityGroupsGet200Response
 */
public class ServersServerIdOsSecurityGroupsGet200ResponseTest {
    private final ServersServerIdOsSecurityGroupsGet200Response model = new ServersServerIdOsSecurityGroupsGet200Response();

    /**
     * Model tests for ServersServerIdOsSecurityGroupsGet200Response
     */
    @Test
    public void testServersServerIdOsSecurityGroupsGet200Response() {
        // TODO: test ServersServerIdOsSecurityGroupsGet200Response
    }

    /**
     * Test the property 'securityGroups'
     */
    @Test
    public void securityGroupsTest() {
        // TODO: test securityGroups
    }

}
