/*
 * Compute API
 * REST API для управления виртуальными машинами
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ServerDetailsLinksInner;
import org.openapitools.client.model.ServersPostRequestServerSecurityGroupsInner;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for ServerDetails
 */
public class ServerDetailsTest {
    private final ServerDetails model = new ServerDetails();

    /**
     * Model tests for ServerDetails
     */
    @Test
    public void testServerDetails() {
        // TODO: test ServerDetails
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'flavor'
     */
    @Test
    public void flavorTest() {
        // TODO: test flavor
    }

    /**
     * Test the property 'hostId'
     */
    @Test
    public void hostIdTest() {
        // TODO: test hostId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'keyName'
     */
    @Test
    public void keyNameTest() {
        // TODO: test keyName
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'accessIPv4'
     */
    @Test
    public void accessIPv4Test() {
        // TODO: test accessIPv4
    }

    /**
     * Test the property 'accessIPv6'
     */
    @Test
    public void accessIPv6Test() {
        // TODO: test accessIPv6
    }

    /**
     * Test the property 'configDrive'
     */
    @Test
    public void configDriveTest() {
        // TODO: test configDrive
    }

    /**
     * Test the property 'osDCFColonDiskConfig'
     */
    @Test
    public void osDCFColonDiskConfigTest() {
        // TODO: test osDCFColonDiskConfig
    }

    /**
     * Test the property 'osEXTAZColonAvailabilityZone'
     */
    @Test
    public void osEXTAZColonAvailabilityZoneTest() {
        // TODO: test osEXTAZColonAvailabilityZone
    }

    /**
     * Test the property 'osEXTSTSColonPowerState'
     */
    @Test
    public void osEXTSTSColonPowerStateTest() {
        // TODO: test osEXTSTSColonPowerState
    }

    /**
     * Test the property 'osEXTSTSColonTaskState'
     */
    @Test
    public void osEXTSTSColonTaskStateTest() {
        // TODO: test osEXTSTSColonTaskState
    }

    /**
     * Test the property 'osEXTSTSColonVmState'
     */
    @Test
    public void osEXTSTSColonVmStateTest() {
        // TODO: test osEXTSTSColonVmState
    }

    /**
     * Test the property 'osExtendedVolumesColonVolumesAttached'
     */
    @Test
    public void osExtendedVolumesColonVolumesAttachedTest() {
        // TODO: test osExtendedVolumesColonVolumesAttached
    }

    /**
     * Test the property 'osSRVUSGColonLaunchedAt'
     */
    @Test
    public void osSRVUSGColonLaunchedAtTest() {
        // TODO: test osSRVUSGColonLaunchedAt
    }

    /**
     * Test the property 'osSRVUSGColonTerminatedAt'
     */
    @Test
    public void osSRVUSGColonTerminatedAtTest() {
        // TODO: test osSRVUSGColonTerminatedAt
    }

    /**
     * Test the property 'progress'
     */
    @Test
    public void progressTest() {
        // TODO: test progress
    }

    /**
     * Test the property 'securityGroups'
     */
    @Test
    public void securityGroupsTest() {
        // TODO: test securityGroups
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'osEXTSERVATTRColonHostname'
     */
    @Test
    public void osEXTSERVATTRColonHostnameTest() {
        // TODO: test osEXTSERVATTRColonHostname
    }

    /**
     * Test the property 'osEXTSERVATTRColonReservationId'
     */
    @Test
    public void osEXTSERVATTRColonReservationIdTest() {
        // TODO: test osEXTSERVATTRColonReservationId
    }

    /**
     * Test the property 'osEXTSERVATTRColonLaunchIndex'
     */
    @Test
    public void osEXTSERVATTRColonLaunchIndexTest() {
        // TODO: test osEXTSERVATTRColonLaunchIndex
    }

    /**
     * Test the property 'osEXTSERVATTRColonKernelId'
     */
    @Test
    public void osEXTSERVATTRColonKernelIdTest() {
        // TODO: test osEXTSERVATTRColonKernelId
    }

    /**
     * Test the property 'osEXTSERVATTRColonRamdiskId'
     */
    @Test
    public void osEXTSERVATTRColonRamdiskIdTest() {
        // TODO: test osEXTSERVATTRColonRamdiskId
    }

    /**
     * Test the property 'osEXTSERVATTRColonRootDeviceName'
     */
    @Test
    public void osEXTSERVATTRColonRootDeviceNameTest() {
        // TODO: test osEXTSERVATTRColonRootDeviceName
    }

    /**
     * Test the property 'osEXTSERVATTRColonUserData'
     */
    @Test
    public void osEXTSERVATTRColonUserDataTest() {
        // TODO: test osEXTSERVATTRColonUserData
    }

}
